module Braintrust
  module Type
    module Converter
      type input = Braintrust::Type::Converter | Class

      type state =
        {
          strictness: bool | :strong,
          exactness: { yes: Integer, no: Integer, maybe: Integer },
          branched: Integer
        }

      def coerce: (top value, state: Braintrust::Type::Converter::state) -> top

      def dump: (top value) -> top

      def self.type_info: (
        {
          const: (nil | bool | Integer | Float | Symbol)?,
          enum: ^-> Braintrust::Type::Converter::input?,
          union: ^-> Braintrust::Type::Converter::input?
        }
        | ^-> Braintrust::Type::Converter::input
        | Braintrust::Type::Converter::input spec
      ) -> (^-> top)

      def self.coerce: (
        Braintrust::Type::Converter::input target,
        top value,
        ?state: Braintrust::Type::Converter::state
      ) -> top

      def self.dump: (
        Braintrust::Type::Converter::input target,
        top value
      ) -> top
    end
  end
end
