module Braintrust
  module Resources
    class ACLs
      def create:
        (
          Braintrust::Models::ACLCreateParams | ::Hash[Symbol, top] params
        ) -> Braintrust::Models::ACL
        | (
          object_id_: String,
          object_type: Braintrust::Models::ACLCreateParams::object_type,
          group_id: String?,
          permission: Braintrust::Models::ACLCreateParams::permission?,
          restrict_object_type: Braintrust::Models::ACLCreateParams::restrict_object_type?,
          role_id: String?,
          user_id: String?,
          request_options: Braintrust::request_opts
        ) -> Braintrust::Models::ACL

      def retrieve:
        (
          String acl_id,
          ?Braintrust::Models::ACLRetrieveParams | ::Hash[Symbol, top] params
        ) -> Braintrust::Models::ACL
        | (
          String acl_id,
          request_options: Braintrust::request_opts
        ) -> Braintrust::Models::ACL

      def list:
        (
          Braintrust::Models::ACLListParams | ::Hash[Symbol, top] params
        ) -> Braintrust::ListObjects[Braintrust::Models::ACL]
        | (
          object_id_: String,
          object_type: Braintrust::Models::ACLListParams::object_type,
          ending_before: String,
          ids: Braintrust::Models::ACLListParams::ids,
          limit: Integer?,
          starting_after: String,
          request_options: Braintrust::request_opts
        ) -> Braintrust::ListObjects[Braintrust::Models::ACL]

      def delete:
        (
          String acl_id,
          ?Braintrust::Models::ACLDeleteParams | ::Hash[Symbol, top] params
        ) -> Braintrust::Models::ACL
        | (
          String acl_id,
          request_options: Braintrust::request_opts
        ) -> Braintrust::Models::ACL

      def batch_update:
        (
          ?Braintrust::Models::ACLBatchUpdateParams | ::Hash[Symbol, top] params
        ) -> Braintrust::Models::ACLBatchUpdateResponse
        | (
          add_acls: ::Array[Braintrust::Models::ACLBatchUpdateParams::AddACL]?,
          remove_acls: ::Array[Braintrust::Models::ACLBatchUpdateParams::RemoveACL]?,
          request_options: Braintrust::request_opts
        ) -> Braintrust::Models::ACLBatchUpdateResponse

      def find_and_delete:
        (
          Braintrust::Models::ACLFindAndDeleteParams
          | ::Hash[Symbol, top] params
        ) -> Braintrust::Models::ACL
        | (
          object_id_: String,
          object_type: Braintrust::Models::ACLFindAndDeleteParams::object_type,
          group_id: String?,
          permission: Braintrust::Models::ACLFindAndDeleteParams::permission?,
          restrict_object_type: Braintrust::Models::ACLFindAndDeleteParams::restrict_object_type?,
          role_id: String?,
          user_id: String?,
          request_options: Braintrust::request_opts
        ) -> Braintrust::Models::ACL

      def initialize: (client: Braintrust::Client) -> void
    end
  end
end
