module Braintrust
  module Resources
    class AISecrets
      def create: (
        name: String,
        ?metadata: ::Hash[Symbol, top?]?,
        ?org_name: String?,
        ?secret: String?,
        ?type: String?,
        ?request_options: Braintrust::request_opts
      ) -> Braintrust::Models::AISecret

      def retrieve: (
        String ai_secret_id,
        ?request_options: Braintrust::request_opts
      ) -> Braintrust::Models::AISecret

      def update: (
        String ai_secret_id,
        ?metadata: ::Hash[Symbol, top?]?,
        ?name: String?,
        ?secret: String?,
        ?type: String?,
        ?request_options: Braintrust::request_opts
      ) -> Braintrust::Models::AISecret

      def list: (
        ?ai_secret_name: String,
        ?ai_secret_type: Braintrust::Models::AISecretListParams::ai_secret_type,
        ?ending_before: String,
        ?ids: Braintrust::Models::AISecretListParams::ids,
        ?limit: Integer?,
        ?org_name: String,
        ?starting_after: String,
        ?request_options: Braintrust::request_opts
      ) -> Braintrust::Internal::ListObjects[Braintrust::Models::AISecret]

      def delete: (
        String ai_secret_id,
        ?request_options: Braintrust::request_opts
      ) -> Braintrust::Models::AISecret

      def find_and_delete: (
        name: String,
        ?org_name: String?,
        ?request_options: Braintrust::request_opts
      ) -> Braintrust::Models::AISecret

      def replace: (
        name: String,
        ?metadata: ::Hash[Symbol, top?]?,
        ?org_name: String?,
        ?secret: String?,
        ?type: String?,
        ?request_options: Braintrust::request_opts
      ) -> Braintrust::Models::AISecret

      def initialize: (client: Braintrust::Client) -> void
    end
  end
end
