module Braintrust
  module Resources
    class APIKeys
      def create: (
        name: String,
        ?org_name: String?,
        ?request_options: Braintrust::request_opts
      ) -> Braintrust::CreateAPIKeyOutput

      def retrieve: (
        String api_key_id,
        ?request_options: Braintrust::request_opts
      ) -> Braintrust::APIKey

      def list: (
        ?api_key_name: String,
        ?ending_before: String,
        ?ids: Braintrust::Models::APIKeyListParams::ids,
        ?limit: Integer?,
        ?org_name: String,
        ?starting_after: String,
        ?request_options: Braintrust::request_opts
      ) -> Braintrust::Internal::ListObjects[Braintrust::APIKey]

      def delete: (
        String api_key_id,
        ?request_options: Braintrust::request_opts
      ) -> Braintrust::APIKey

      def initialize: (client: Braintrust::Client) -> void
    end
  end
end
