module Braintrust
  module Resources
    class Organizations
      attr_reader members: Braintrust::Resources::Organizations::Members

      def retrieve: (
        String organization_id,
        ?request_options: Braintrust::request_opts
      ) -> Braintrust::Organization

      def update: (
        String organization_id,
        ?api_url: String?,
        ?is_universal_api: bool?,
        ?name: String?,
        ?proxy_url: String?,
        ?realtime_url: String?,
        ?request_options: Braintrust::request_opts
      ) -> Braintrust::Organization

      def list: (
        ?ending_before: String,
        ?ids: Braintrust::Models::OrganizationListParams::ids,
        ?limit: Integer?,
        ?org_name: String,
        ?starting_after: String,
        ?request_options: Braintrust::request_opts
      ) -> Braintrust::Internal::ListObjects[Braintrust::Organization]

      def delete: (
        String organization_id,
        ?request_options: Braintrust::request_opts
      ) -> Braintrust::Organization

      def initialize: (client: Braintrust::Client) -> void
    end
  end
end
