module Braintrust
  module Resources
    class TopLevel
      def hello_world: (?request_options: Braintrust::request_opts) -> String

      def initialize: (client: Braintrust::Client) -> void
    end
  end
end
