module Braintrust
  module Resources
    class Views
      def create: (
        name: String,
        object_id_: String,
        object_type: Braintrust::Models::acl_object_type,
        view_type: Braintrust::Models::ViewCreateParams::view_type?,
        ?deleted_at: Time?,
        ?options: Braintrust::ViewOptions?,
        ?user_id: String?,
        ?view_data: Braintrust::ViewData?,
        ?request_options: Braintrust::request_opts
      ) -> Braintrust::View

      def retrieve: (
        String view_id,
        object_id_: String,
        object_type: Braintrust::Models::acl_object_type,
        ?request_options: Braintrust::request_opts
      ) -> Braintrust::View

      def update: (
        String view_id,
        object_id_: String,
        object_type: Braintrust::Models::acl_object_type,
        ?name: String?,
        ?options: Braintrust::ViewOptions?,
        ?user_id: String?,
        ?view_data: Braintrust::ViewData?,
        ?view_type: Braintrust::Models::ViewUpdateParams::view_type?,
        ?request_options: Braintrust::request_opts
      ) -> Braintrust::View

      def list: (
        object_id_: String,
        object_type: Braintrust::Models::acl_object_type,
        ?ending_before: String,
        ?ids: Braintrust::Models::ViewListParams::ids,
        ?limit: Integer?,
        ?starting_after: String,
        ?view_name: String,
        ?view_type: Braintrust::Models::view_type?,
        ?request_options: Braintrust::request_opts
      ) -> Braintrust::Internal::ListObjects[Braintrust::View]

      def delete: (
        String view_id,
        object_id_: String,
        object_type: Braintrust::Models::acl_object_type,
        ?request_options: Braintrust::request_opts
      ) -> Braintrust::View

      def replace: (
        name: String,
        object_id_: String,
        object_type: Braintrust::Models::acl_object_type,
        view_type: Braintrust::Models::ViewReplaceParams::view_type?,
        ?deleted_at: Time?,
        ?options: Braintrust::ViewOptions?,
        ?user_id: String?,
        ?view_data: Braintrust::ViewData?,
        ?request_options: Braintrust::request_opts
      ) -> Braintrust::View

      def initialize: (client: Braintrust::Client) -> void
    end
  end
end
