module Braintrust
  module Resources
    class Views
      def create:
        (
          Braintrust::Models::ViewCreateParams | ::Hash[Symbol, top] params
        ) -> Braintrust::Models::View
        | (
          name: String,
          object_id_: String,
          object_type: Braintrust::Models::acl_object_type,
          view_type: Braintrust::Models::ViewCreateParams::view_type?,
          ?deleted_at: Time?,
          ?options: Braintrust::Models::ViewOptions?,
          ?user_id: String?,
          ?view_data: Braintrust::Models::ViewData?,
          ?request_options: Braintrust::request_opts
        ) -> Braintrust::Models::View

      def retrieve:
        (
          String view_id,
          Braintrust::Models::ViewRetrieveParams | ::Hash[Symbol, top] params
        ) -> Braintrust::Models::View
        | (
          String view_id,
          object_id_: String,
          object_type: Braintrust::Models::acl_object_type,
          ?request_options: Braintrust::request_opts
        ) -> Braintrust::Models::View

      def update:
        (
          String view_id,
          Braintrust::Models::ViewUpdateParams | ::Hash[Symbol, top] params
        ) -> Braintrust::Models::View
        | (
          String view_id,
          object_id_: String,
          object_type: Braintrust::Models::acl_object_type,
          ?name: String?,
          ?options: Braintrust::Models::ViewOptions?,
          ?user_id: String?,
          ?view_data: Braintrust::Models::ViewData?,
          ?view_type: Braintrust::Models::ViewUpdateParams::view_type?,
          ?request_options: Braintrust::request_opts
        ) -> Braintrust::Models::View

      def list:
        (
          Braintrust::Models::ViewListParams | ::Hash[Symbol, top] params
        ) -> Braintrust::ListObjects[Braintrust::Models::View]
        | (
          object_id_: String,
          object_type: Braintrust::Models::acl_object_type,
          ?ending_before: String,
          ?ids: Braintrust::Models::ViewListParams::ids,
          ?limit: Integer?,
          ?starting_after: String,
          ?view_name: String,
          ?view_type: Braintrust::Models::view_type?,
          ?request_options: Braintrust::request_opts
        ) -> Braintrust::ListObjects[Braintrust::Models::View]

      def delete:
        (
          String view_id,
          Braintrust::Models::ViewDeleteParams | ::Hash[Symbol, top] params
        ) -> Braintrust::Models::View
        | (
          String view_id,
          object_id_: String,
          object_type: Braintrust::Models::acl_object_type,
          ?request_options: Braintrust::request_opts
        ) -> Braintrust::Models::View

      def replace:
        (
          Braintrust::Models::ViewReplaceParams | ::Hash[Symbol, top] params
        ) -> Braintrust::Models::View
        | (
          name: String,
          object_id_: String,
          object_type: Braintrust::Models::acl_object_type,
          view_type: Braintrust::Models::ViewReplaceParams::view_type?,
          ?deleted_at: Time?,
          ?options: Braintrust::Models::ViewOptions?,
          ?user_id: String?,
          ?view_data: Braintrust::Models::ViewData?,
          ?request_options: Braintrust::request_opts
        ) -> Braintrust::Models::View

      def initialize: (client: Braintrust::Client) -> void
    end
  end
end
