module Braintrust
  module Models
    type ai_secret =
      {
        id: String,
        name: String,
        org_id: String,
        created: Time?,
        metadata: ::Hash[Symbol, top?]?,
        preview_secret: String?,
        type: String?,
        updated_at: Time?
      }

    class AISecret < Braintrust::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor name: String

      attr_accessor org_id: String

      attr_accessor created: Time?

      attr_accessor metadata: ::Hash[Symbol, top?]?

      attr_accessor preview_secret: String?

      attr_accessor type: String?

      attr_accessor updated_at: Time?

      def initialize: (
        id: String,
        name: String,
        org_id: String,
        ?created: Time?,
        ?metadata: ::Hash[Symbol, top?]?,
        ?preview_secret: String?,
        ?type: String?,
        ?updated_at: Time?
      ) -> void

      def to_hash: -> Braintrust::Models::ai_secret
    end
  end
end
