module Braintrust
  module Models
    type acl_find_and_delete_params =
      {
        object_id_: String,
        object_type: Braintrust::Models::acl_object_type,
        group_id: String?,
        permission: Braintrust::Models::permission?,
        restrict_object_type: Braintrust::Models::acl_object_type?,
        role_id: String?,
        user_id: String?
      }
      & Braintrust::request_parameters

    class ACLFindAndDeleteParams < Braintrust::BaseModel
      extend Braintrust::RequestParameters::Converter
      include Braintrust::RequestParameters

      attr_accessor object_id_: String

      attr_accessor object_type: Braintrust::Models::acl_object_type

      attr_accessor group_id: String?

      attr_accessor permission: Braintrust::Models::permission?

      attr_accessor restrict_object_type: Braintrust::Models::acl_object_type?

      attr_accessor role_id: String?

      attr_accessor user_id: String?

      def initialize:
        (
          object_id_: String,
          object_type: Braintrust::Models::acl_object_type,
          ?group_id: String?,
          ?permission: Braintrust::Models::permission?,
          ?restrict_object_type: Braintrust::Models::acl_object_type?,
          ?role_id: String?,
          ?user_id: String?,
          ?request_options: Braintrust::request_opts
        ) -> void
        | (
          ?Braintrust::Models::acl_find_and_delete_params
          | Braintrust::BaseModel data
        ) -> void

      def to_hash: -> Braintrust::Models::acl_find_and_delete_params
    end
  end
end
