module Braintrust
  module Models
    type acl_batch_update_params =
      {
        add_acls: ::Array[Braintrust::Models::ACLBatchUpdateParams::AddACL]?,
        remove_acls: ::Array[Braintrust::Models::ACLBatchUpdateParams::RemoveACL]?
      }
      & Braintrust::request_parameters

    class ACLBatchUpdateParams < Braintrust::BaseModel
      extend Braintrust::RequestParameters::Converter
      include Braintrust::RequestParameters

      attr_accessor add_acls: ::Array[Braintrust::Models::ACLBatchUpdateParams::AddACL]?

      attr_accessor remove_acls: ::Array[Braintrust::Models::ACLBatchUpdateParams::RemoveACL]?

      def initialize:
        (
          add_acls: ::Array[Braintrust::Models::ACLBatchUpdateParams::AddACL]?,
          remove_acls: ::Array[Braintrust::Models::ACLBatchUpdateParams::RemoveACL]?,
          request_options: Braintrust::request_opts
        ) -> void
        | (
          ?Braintrust::Models::acl_batch_update_params
          | Braintrust::BaseModel data
        ) -> void

      def to_hash: -> Braintrust::Models::acl_batch_update_params

      type add_acl =
        {
          object_id_: String,
          object_type: Braintrust::Models::ACLBatchUpdateParams::AddACL::object_type,
          group_id: String?,
          permission: Braintrust::Models::ACLBatchUpdateParams::AddACL::permission?,
          restrict_object_type: Braintrust::Models::ACLBatchUpdateParams::AddACL::restrict_object_type?,
          role_id: String?,
          user_id: String?
        }

      class AddACL < Braintrust::BaseModel
        attr_accessor object_id_: String

        attr_accessor object_type: Braintrust::Models::ACLBatchUpdateParams::AddACL::object_type

        attr_accessor group_id: String?

        attr_accessor permission: Braintrust::Models::ACLBatchUpdateParams::AddACL::permission?

        attr_accessor restrict_object_type: Braintrust::Models::ACLBatchUpdateParams::AddACL::restrict_object_type?

        attr_accessor role_id: String?

        attr_accessor user_id: String?

        def initialize:
          (
            object_id_: String,
            object_type: Braintrust::Models::ACLBatchUpdateParams::AddACL::object_type,
            group_id: String?,
            permission: Braintrust::Models::ACLBatchUpdateParams::AddACL::permission?,
            restrict_object_type: Braintrust::Models::ACLBatchUpdateParams::AddACL::restrict_object_type?,
            role_id: String?,
            user_id: String?
          ) -> void
          | (
            ?Braintrust::Models::ACLBatchUpdateParams::add_acl
            | Braintrust::BaseModel data
          ) -> void

        def to_hash: -> Braintrust::Models::ACLBatchUpdateParams::add_acl

        type object_type =
          :organization
          | :project
          | :experiment
          | :dataset
          | :prompt
          | :prompt_session
          | :group
          | :role
          | :org_member
          | :project_log
          | :org_project

        class ObjectType < Braintrust::Enum
          ORGANIZATION: :organization
          PROJECT: :project
          EXPERIMENT: :experiment
          DATASET: :dataset
          PROMPT: :prompt
          PROMPT_SESSION: :prompt_session
          GROUP: :group
          ROLE: :role
          ORG_MEMBER: :org_member
          PROJECT_LOG: :project_log
          ORG_PROJECT: :org_project

          def self.values: -> ::Array[Braintrust::Models::ACLBatchUpdateParams::AddACL::object_type]
        end

        type permission =
          :create
          | :read
          | :update
          | :delete
          | :create_acls
          | :read_acls
          | :update_acls
          | :delete_acls

        class Permission < Braintrust::Enum
          CREATE: :create
          READ: :read
          UPDATE: :update
          DELETE: :delete
          CREATE_ACLS: :create_acls
          READ_ACLS: :read_acls
          UPDATE_ACLS: :update_acls
          DELETE_ACLS: :delete_acls

          def self.values: -> ::Array[Braintrust::Models::ACLBatchUpdateParams::AddACL::permission]
        end

        type restrict_object_type =
          :organization
          | :project
          | :experiment
          | :dataset
          | :prompt
          | :prompt_session
          | :group
          | :role
          | :org_member
          | :project_log
          | :org_project

        class RestrictObjectType < Braintrust::Enum
          ORGANIZATION: :organization
          PROJECT: :project
          EXPERIMENT: :experiment
          DATASET: :dataset
          PROMPT: :prompt
          PROMPT_SESSION: :prompt_session
          GROUP: :group
          ROLE: :role
          ORG_MEMBER: :org_member
          PROJECT_LOG: :project_log
          ORG_PROJECT: :org_project

          def self.values: -> ::Array[Braintrust::Models::ACLBatchUpdateParams::AddACL::restrict_object_type]
        end
      end

      type remove_acl =
        {
          object_id_: String,
          object_type: Braintrust::Models::ACLBatchUpdateParams::RemoveACL::object_type,
          group_id: String?,
          permission: Braintrust::Models::ACLBatchUpdateParams::RemoveACL::permission?,
          restrict_object_type: Braintrust::Models::ACLBatchUpdateParams::RemoveACL::restrict_object_type?,
          role_id: String?,
          user_id: String?
        }

      class RemoveACL < Braintrust::BaseModel
        attr_accessor object_id_: String

        attr_accessor object_type: Braintrust::Models::ACLBatchUpdateParams::RemoveACL::object_type

        attr_accessor group_id: String?

        attr_accessor permission: Braintrust::Models::ACLBatchUpdateParams::RemoveACL::permission?

        attr_accessor restrict_object_type: Braintrust::Models::ACLBatchUpdateParams::RemoveACL::restrict_object_type?

        attr_accessor role_id: String?

        attr_accessor user_id: String?

        def initialize:
          (
            object_id_: String,
            object_type: Braintrust::Models::ACLBatchUpdateParams::RemoveACL::object_type,
            group_id: String?,
            permission: Braintrust::Models::ACLBatchUpdateParams::RemoveACL::permission?,
            restrict_object_type: Braintrust::Models::ACLBatchUpdateParams::RemoveACL::restrict_object_type?,
            role_id: String?,
            user_id: String?
          ) -> void
          | (
            ?Braintrust::Models::ACLBatchUpdateParams::remove_acl
            | Braintrust::BaseModel data
          ) -> void

        def to_hash: -> Braintrust::Models::ACLBatchUpdateParams::remove_acl

        type object_type =
          :organization
          | :project
          | :experiment
          | :dataset
          | :prompt
          | :prompt_session
          | :group
          | :role
          | :org_member
          | :project_log
          | :org_project

        class ObjectType < Braintrust::Enum
          ORGANIZATION: :organization
          PROJECT: :project
          EXPERIMENT: :experiment
          DATASET: :dataset
          PROMPT: :prompt
          PROMPT_SESSION: :prompt_session
          GROUP: :group
          ROLE: :role
          ORG_MEMBER: :org_member
          PROJECT_LOG: :project_log
          ORG_PROJECT: :org_project

          def self.values: -> ::Array[Braintrust::Models::ACLBatchUpdateParams::RemoveACL::object_type]
        end

        type permission =
          :create
          | :read
          | :update
          | :delete
          | :create_acls
          | :read_acls
          | :update_acls
          | :delete_acls

        class Permission < Braintrust::Enum
          CREATE: :create
          READ: :read
          UPDATE: :update
          DELETE: :delete
          CREATE_ACLS: :create_acls
          READ_ACLS: :read_acls
          UPDATE_ACLS: :update_acls
          DELETE_ACLS: :delete_acls

          def self.values: -> ::Array[Braintrust::Models::ACLBatchUpdateParams::RemoveACL::permission]
        end

        type restrict_object_type =
          :organization
          | :project
          | :experiment
          | :dataset
          | :prompt
          | :prompt_session
          | :group
          | :role
          | :org_member
          | :project_log
          | :org_project

        class RestrictObjectType < Braintrust::Enum
          ORGANIZATION: :organization
          PROJECT: :project
          EXPERIMENT: :experiment
          DATASET: :dataset
          PROMPT: :prompt
          PROMPT_SESSION: :prompt_session
          GROUP: :group
          ROLE: :role
          ORG_MEMBER: :org_member
          PROJECT_LOG: :project_log
          ORG_PROJECT: :org_project

          def self.values: -> ::Array[Braintrust::Models::ACLBatchUpdateParams::RemoveACL::restrict_object_type]
        end
      end
    end
  end
end
