module Braintrust
  module Models
    type ai_secret_list_params =
      {
        ai_secret_name: String,
        ai_secret_type: Braintrust::Models::AISecretListParams::ai_secret_type,
        ending_before: String,
        ids: Braintrust::Models::AISecretListParams::ids,
        limit: Integer?,
        org_name: String,
        starting_after: String
      }
      & Braintrust::request_parameters

    class AISecretListParams < Braintrust::BaseModel
      extend Braintrust::Type::RequestParameters::Converter
      include Braintrust::RequestParameters

      attr_reader ai_secret_name: String?

      def ai_secret_name=: (String) -> String

      attr_reader ai_secret_type: Braintrust::Models::AISecretListParams::ai_secret_type?

      def ai_secret_type=: (
        Braintrust::Models::AISecretListParams::ai_secret_type
      ) -> Braintrust::Models::AISecretListParams::ai_secret_type

      attr_reader ending_before: String?

      def ending_before=: (String) -> String

      attr_reader ids: Braintrust::Models::AISecretListParams::ids?

      def ids=: (
        Braintrust::Models::AISecretListParams::ids
      ) -> Braintrust::Models::AISecretListParams::ids

      attr_accessor limit: Integer?

      attr_reader org_name: String?

      def org_name=: (String) -> String

      attr_reader starting_after: String?

      def starting_after=: (String) -> String

      def initialize: (
        ?ai_secret_name: String,
        ?ai_secret_type: Braintrust::Models::AISecretListParams::ai_secret_type,
        ?ending_before: String,
        ?ids: Braintrust::Models::AISecretListParams::ids,
        ?limit: Integer?,
        ?org_name: String,
        ?starting_after: String,
        ?request_options: Braintrust::request_opts
      ) -> void

      def to_hash: -> Braintrust::Models::ai_secret_list_params

      type ai_secret_type = String | ::Array[String]

      module AISecretType
        extend Braintrust::Union

        def self?.variants: -> [String, ::Array[String]]

        type string_array = ::Array[String]

        StringArray: string_array
      end

      type ids = String | ::Array[String]

      module IDs
        extend Braintrust::Union

        def self?.variants: -> [String, ::Array[String]]

        type string_array = ::Array[String]

        StringArray: string_array
      end
    end
  end
end
