module Braintrust
  module Models
    type ai_secret_update_params =
      {
        metadata: ::Hash[Symbol, top?]?,
        name: String?,
        secret: String?,
        type: String?
      }
      & Braintrust::request_parameters

    class AISecretUpdateParams < Braintrust::BaseModel
      extend Braintrust::RequestParameters::Converter
      include Braintrust::RequestParameters

      attr_accessor metadata: ::Hash[Symbol, top?]?

      attr_accessor name: String?

      attr_accessor secret: String?

      attr_accessor type: String?

      def initialize: (
        ?metadata: ::Hash[Symbol, top?]?,
        ?name: String?,
        ?secret: String?,
        ?type: String?,
        ?request_options: Braintrust::request_opts
      ) -> void

      def to_hash: -> Braintrust::Models::ai_secret_update_params
    end
  end
end
