module Braintrust
  module Models
    type ai_secret_replace_params =
      {
        name: String,
        metadata: ::Hash[Symbol, top?]?,
        org_name: String?,
        secret: String?,
        type: String?
      }
      & Braintrust::request_parameters

    class AISecretReplaceParams < Braintrust::BaseModel
      extend Braintrust::RequestParameters::Converter
      include Braintrust::RequestParameters

      attr_accessor name: String

      attr_accessor metadata: ::Hash[Symbol, top?]?

      attr_accessor org_name: String?

      attr_accessor secret: String?

      attr_accessor type: String?

      def initialize:
        (
          name: String,
          ?metadata: ::Hash[Symbol, top?]?,
          ?org_name: String?,
          ?secret: String?,
          ?type: String?,
          ?request_options: Braintrust::request_opts
        ) -> void
        | (
          ?Braintrust::Models::ai_secret_replace_params
          | Braintrust::BaseModel data
        ) -> void

      def to_hash: -> Braintrust::Models::ai_secret_replace_params
    end
  end
end
