module Braintrust
  module Models
    type api_key_delete_params = {  } & Braintrust::request_parameters

    class APIKeyDeleteParams < Braintrust::BaseModel
      extend Braintrust::RequestParameters::Converter
      include Braintrust::RequestParameters

      def initialize:
        (request_options: Braintrust::request_opts) -> void
        | (
          ?Braintrust::Models::api_key_delete_params
          | Braintrust::BaseModel data
        ) -> void

      def to_hash: -> Braintrust::Models::api_key_delete_params
    end
  end
end
