module Braintrust
  module Models
    type api_key_list_params =
      {
        api_key_name: String,
        ending_before: String,
        ids: Braintrust::Models::APIKeyListParams::ids,
        limit: Integer?,
        org_name: String,
        starting_after: String
      }
      & Braintrust::request_parameters

    class APIKeyListParams < Braintrust::BaseModel
      extend Braintrust::Type::RequestParameters::Converter
      include Braintrust::RequestParameters

      attr_reader api_key_name: String?

      def api_key_name=: (String) -> String

      attr_reader ending_before: String?

      def ending_before=: (String) -> String

      attr_reader ids: Braintrust::Models::APIKeyListParams::ids?

      def ids=: (
        Braintrust::Models::APIKeyListParams::ids
      ) -> Braintrust::Models::APIKeyListParams::ids

      attr_accessor limit: Integer?

      attr_reader org_name: String?

      def org_name=: (String) -> String

      attr_reader starting_after: String?

      def starting_after=: (String) -> String

      def initialize: (
        ?api_key_name: String,
        ?ending_before: String,
        ?ids: Braintrust::Models::APIKeyListParams::ids,
        ?limit: Integer?,
        ?org_name: String,
        ?starting_after: String,
        ?request_options: Braintrust::request_opts
      ) -> void

      def to_hash: -> Braintrust::Models::api_key_list_params

      type ids = String | ::Array[String]

      module IDs
        extend Braintrust::Union

        def self?.variants: -> [String, ::Array[String]]

        type string_array = ::Array[String]

        StringArray: string_array
      end
    end
  end
end
