module Braintrust
  module Models
    type api_key =
      {
        id: String,
        name: String,
        preview_name: String,
        created: Time?,
        org_id: String?,
        user_id: String?
      }

    class APIKey < Braintrust::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor name: String

      attr_accessor preview_name: String

      attr_accessor created: Time?

      attr_accessor org_id: String?

      attr_accessor user_id: String?

      def initialize: (
        id: String,
        name: String,
        preview_name: String,
        ?created: Time?,
        ?org_id: String?,
        ?user_id: String?
      ) -> void
    end
  end
end
