module Braintrust
  module Models
    type api_key_retrieve_params =
      {  } & Braintrust::Internal::Type::request_parameters

    class APIKeyRetrieveParams < Braintrust::BaseModel
      extend Braintrust::Internal::Type::RequestParameters::Converter
      include Braintrust::Internal::Type::RequestParameters

      def initialize: (?request_options: Braintrust::request_opts) -> void

      def to_hash: -> Braintrust::Models::api_key_retrieve_params
    end
  end
end
