module Braintrust
  module Models
    type chat_completion_content_part_text =
      { type: Braintrust::ChatCompletionContentPartText::type_, text: String }

    class ChatCompletionContentPartText < Braintrust::Internal::Type::BaseModel
      attr_accessor type: Braintrust::ChatCompletionContentPartText::type_

      attr_reader text: String?

      def text=: (String) -> String

      def initialize: (
        type: Braintrust::ChatCompletionContentPartText::type_,
        ?text: String
      ) -> void

      type type_ = :text

      module Type
        extend Braintrust::Internal::Type::Enum

        TEXT: :text

        def self?.values: -> ::Array[Braintrust::ChatCompletionContentPartText::type_]
      end
    end
  end
end
