module Braintrust
  module Models
    type code_bundle =
      {
        bundle_id: String,
        location: Braintrust::CodeBundle::location,
        runtime_context: Braintrust::CodeBundle::RuntimeContext,
        preview: String?
      }

    class CodeBundle < Braintrust::Internal::Type::BaseModel
      attr_accessor bundle_id: String

      attr_accessor location: Braintrust::CodeBundle::location

      attr_accessor runtime_context: Braintrust::CodeBundle::RuntimeContext

      attr_accessor preview: String?

      def initialize: (
        bundle_id: String,
        location: Braintrust::CodeBundle::location,
        runtime_context: Braintrust::CodeBundle::RuntimeContext,
        ?preview: String?
      ) -> void

      type location =
        Braintrust::CodeBundle::Location::Experiment
        | Braintrust::CodeBundle::Location::Function

      module Location
        extend Braintrust::Internal::Type::Union

        type experiment =
          {
            eval_name: String,
            position: Braintrust::CodeBundle::Location::Experiment::position,
            type: Braintrust::CodeBundle::Location::Experiment::type_
          }

        class Experiment < Braintrust::Internal::Type::BaseModel
          attr_accessor eval_name: String

          attr_accessor position: Braintrust::CodeBundle::Location::Experiment::position

          attr_accessor type: Braintrust::CodeBundle::Location::Experiment::type_

          def initialize: (
            eval_name: String,
            position: Braintrust::CodeBundle::Location::Experiment::position,
            type: Braintrust::CodeBundle::Location::Experiment::type_
          ) -> void

          type position =
            Braintrust::CodeBundle::Location::Experiment::Position::Type
            | Braintrust::CodeBundle::Location::Experiment::Position::Scorer

          module Position
            extend Braintrust::Internal::Type::Union

            type type_ =
              {
                type: Braintrust::CodeBundle::Location::Experiment::Position::Type::type_
              }

            class Type < Braintrust::Internal::Type::BaseModel
              attr_accessor type: Braintrust::CodeBundle::Location::Experiment::Position::Type::type_

              def initialize: (
                type: Braintrust::CodeBundle::Location::Experiment::Position::Type::type_
              ) -> void

              type type_ = :task

              module Type
                extend Braintrust::Internal::Type::Enum

                TASK: :task

                def self?.values: -> ::Array[Braintrust::CodeBundle::Location::Experiment::Position::Type::type_]
              end
            end

            type scorer =
              {
                index: Integer,
                type: Braintrust::CodeBundle::Location::Experiment::Position::Scorer::type_
              }

            class Scorer < Braintrust::Internal::Type::BaseModel
              attr_accessor index: Integer

              attr_accessor type: Braintrust::CodeBundle::Location::Experiment::Position::Scorer::type_

              def initialize: (
                index: Integer,
                type: Braintrust::CodeBundle::Location::Experiment::Position::Scorer::type_
              ) -> void

              type type_ = :scorer

              module Type
                extend Braintrust::Internal::Type::Enum

                SCORER: :scorer

                def self?.values: -> ::Array[Braintrust::CodeBundle::Location::Experiment::Position::Scorer::type_]
              end
            end

            def self?.variants: -> ::Array[Braintrust::CodeBundle::Location::Experiment::position]
          end

          type type_ = :experiment

          module Type
            extend Braintrust::Internal::Type::Enum

            EXPERIMENT: :experiment

            def self?.values: -> ::Array[Braintrust::CodeBundle::Location::Experiment::type_]
          end
        end

        type function =
          {
            index: Integer,
            type: Braintrust::CodeBundle::Location::Function::type_
          }

        class Function < Braintrust::Internal::Type::BaseModel
          attr_accessor index: Integer

          attr_accessor type: Braintrust::CodeBundle::Location::Function::type_

          def initialize: (
            index: Integer,
            type: Braintrust::CodeBundle::Location::Function::type_
          ) -> void

          type type_ = :function

          module Type
            extend Braintrust::Internal::Type::Enum

            FUNCTION: :function

            def self?.values: -> ::Array[Braintrust::CodeBundle::Location::Function::type_]
          end
        end

        def self?.variants: -> ::Array[Braintrust::CodeBundle::location]
      end

      type runtime_context =
        {
          runtime: Braintrust::CodeBundle::RuntimeContext::runtime,
          version: String
        }

      class RuntimeContext < Braintrust::Internal::Type::BaseModel
        attr_accessor runtime: Braintrust::CodeBundle::RuntimeContext::runtime

        attr_accessor version: String

        def initialize: (
          runtime: Braintrust::CodeBundle::RuntimeContext::runtime,
          version: String
        ) -> void

        type runtime = :node | :python

        module Runtime
          extend Braintrust::Internal::Type::Enum

          NODE: :node
          PYTHON: :python

          def self?.values: -> ::Array[Braintrust::CodeBundle::RuntimeContext::runtime]
        end
      end
    end
  end
end
