module Braintrust
  module Models
    type cross_object_insert_response =
      {
        dataset: ::Hash[Symbol, Braintrust::Models::InsertEventsResponse]?,
        experiment: ::Hash[Symbol, Braintrust::Models::InsertEventsResponse]?,
        project_logs: ::Hash[Symbol, Braintrust::Models::InsertEventsResponse]?
      }

    class CrossObjectInsertResponse < Braintrust::BaseModel
      attr_accessor dataset: ::Hash[Symbol, Braintrust::Models::InsertEventsResponse]?

      attr_accessor experiment: ::Hash[Symbol, Braintrust::Models::InsertEventsResponse]?

      attr_accessor project_logs: ::Hash[Symbol, Braintrust::Models::InsertEventsResponse]?

      def initialize:
        (
          ?dataset: ::Hash[Symbol, Braintrust::Models::InsertEventsResponse]?,
          ?experiment: ::Hash[Symbol, Braintrust::Models::InsertEventsResponse]?,
          ?project_logs: ::Hash[Symbol, Braintrust::Models::InsertEventsResponse]?
        ) -> void
        | (
          ?Braintrust::Models::cross_object_insert_response
          | Braintrust::BaseModel data
        ) -> void

      def to_hash: -> Braintrust::Models::cross_object_insert_response
    end
  end
end
