module Braintrust
  module Models
    type feedback_project_logs_item =
      {
        id: String,
        comment: String?,
        expected: top,
        metadata: ::Hash[Symbol, top?]?,
        scores: ::Hash[Symbol, Float?]?,
        source: Braintrust::FeedbackProjectLogsItem::source?,
        tags: ::Array[String]?
      }

    class FeedbackProjectLogsItem < Braintrust::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor comment: String?

      attr_reader expected: top?

      def expected=: (top) -> top

      attr_accessor metadata: ::Hash[Symbol, top?]?

      attr_accessor scores: ::Hash[Symbol, Float?]?

      attr_accessor source: Braintrust::FeedbackProjectLogsItem::source?

      attr_accessor tags: ::Array[String]?

      def initialize: (
        id: String,
        ?comment: String?,
        ?expected: top,
        ?metadata: ::Hash[Symbol, top?]?,
        ?scores: ::Hash[Symbol, Float?]?,
        ?source: Braintrust::FeedbackProjectLogsItem::source?,
        ?tags: ::Array[String]?
      ) -> void

      type source = :app | :api | :external

      module Source
        extend Braintrust::Internal::Type::Enum

        APP: :app
        API: :api
        EXTERNAL: :external

        def self?.values: -> ::Array[Braintrust::FeedbackProjectLogsItem::source]
      end
    end
  end
end
