module Braintrust
  module Models
    type fetch_project_logs_events_response =
      { events: ::Array[Braintrust::Models::ProjectLogsEvent], cursor: String? }

    class FetchProjectLogsEventsResponse < Braintrust::BaseModel
      attr_accessor events: ::Array[Braintrust::Models::ProjectLogsEvent]

      attr_accessor cursor: String?

      def initialize:
        (
          events: ::Array[Braintrust::Models::ProjectLogsEvent],
          cursor: String?
        ) -> void
        | (
          ?Braintrust::Models::fetch_project_logs_events_response
          | Braintrust::BaseModel data
        ) -> void

      def to_hash: -> Braintrust::Models::fetch_project_logs_events_response
    end
  end
end
