module Braintrust
  module Models
    type function_replace_params =
      {
        function_data: Braintrust::Models::FunctionReplaceParams::function_data,
        name: String,
        project_id: String,
        slug: String,
        description: String?,
        function_schema: Braintrust::FunctionReplaceParams::FunctionSchema?,
        function_type: Braintrust::Models::FunctionReplaceParams::function_type?,
        origin: Braintrust::FunctionReplaceParams::Origin?,
        prompt_data: Braintrust::PromptData?,
        tags: ::Array[String]?
      }
      & Braintrust::Internal::Type::request_parameters

    class FunctionReplaceParams < Braintrust::Internal::Type::BaseModel
      extend Braintrust::Internal::Type::RequestParameters::Converter
      include Braintrust::Internal::Type::RequestParameters

      attr_accessor function_data: Braintrust::Models::FunctionReplaceParams::function_data

      attr_accessor name: String

      attr_accessor project_id: String

      attr_accessor slug: String

      attr_accessor description: String?

      attr_accessor function_schema: Braintrust::FunctionReplaceParams::FunctionSchema?

      attr_accessor function_type: Braintrust::Models::FunctionReplaceParams::function_type?

      attr_accessor origin: Braintrust::FunctionReplaceParams::Origin?

      attr_accessor prompt_data: Braintrust::PromptData?

      attr_accessor tags: ::Array[String]?

      def initialize: (
        function_data: Braintrust::Models::FunctionReplaceParams::function_data,
        name: String,
        project_id: String,
        slug: String,
        ?description: String?,
        ?function_schema: Braintrust::FunctionReplaceParams::FunctionSchema?,
        ?function_type: Braintrust::Models::FunctionReplaceParams::function_type?,
        ?origin: Braintrust::FunctionReplaceParams::Origin?,
        ?prompt_data: Braintrust::PromptData?,
        ?tags: ::Array[String]?,
        ?request_options: Braintrust::request_opts
      ) -> void

      type function_data =
        Braintrust::FunctionReplaceParams::FunctionData::Prompt
        | Braintrust::FunctionReplaceParams::FunctionData::Code
        | Braintrust::FunctionReplaceParams::FunctionData::Global

      module FunctionData
        extend Braintrust::Internal::Type::Union

        type prompt =
          {
            type: Braintrust::FunctionReplaceParams::FunctionData::Prompt::type_
          }

        class Prompt < Braintrust::Internal::Type::BaseModel
          attr_accessor type: Braintrust::FunctionReplaceParams::FunctionData::Prompt::type_

          def initialize: (
            type: Braintrust::FunctionReplaceParams::FunctionData::Prompt::type_
          ) -> void

          type type_ = :prompt

          module Type
            extend Braintrust::Internal::Type::Enum

            PROMPT: :prompt

            def self?.values: -> ::Array[Braintrust::FunctionReplaceParams::FunctionData::Prompt::type_]
          end
        end

        type code =
          {
            data: Braintrust::FunctionReplaceParams::FunctionData::Code::data,
            type: Braintrust::FunctionReplaceParams::FunctionData::Code::type_
          }

        class Code < Braintrust::Internal::Type::BaseModel
          attr_accessor data: Braintrust::FunctionReplaceParams::FunctionData::Code::data

          attr_accessor type: Braintrust::FunctionReplaceParams::FunctionData::Code::type_

          def initialize: (
            data: Braintrust::FunctionReplaceParams::FunctionData::Code::data,
            type: Braintrust::FunctionReplaceParams::FunctionData::Code::type_
          ) -> void

          type data =
            Braintrust::FunctionReplaceParams::FunctionData::Code::Data::Bundle
            | Braintrust::FunctionReplaceParams::FunctionData::Code::Data::Inline

          module Data
            extend Braintrust::Internal::Type::Union

            type bundle =
              {
                type: Braintrust::FunctionReplaceParams::FunctionData::Code::Data::Bundle::type_
              }

            class Bundle < Braintrust::Models::CodeBundle
              def `type`: -> Braintrust::FunctionReplaceParams::FunctionData::Code::Data::Bundle::type_

              def type=: (
                Braintrust::FunctionReplaceParams::FunctionData::Code::Data::Bundle::type_ _
              ) -> Braintrust::FunctionReplaceParams::FunctionData::Code::Data::Bundle::type_

              def initialize: (
                type: Braintrust::FunctionReplaceParams::FunctionData::Code::Data::Bundle::type_
              ) -> void

              type type_ = :bundle

              module Type
                extend Braintrust::Internal::Type::Enum

                BUNDLE: :bundle

                def self?.values: -> ::Array[Braintrust::FunctionReplaceParams::FunctionData::Code::Data::Bundle::type_]
              end
            end

            type inline =
              {
                code: String,
                runtime_context: Braintrust::FunctionReplaceParams::FunctionData::Code::Data::Inline::RuntimeContext,
                type: Braintrust::FunctionReplaceParams::FunctionData::Code::Data::Inline::type_
              }

            class Inline < Braintrust::Internal::Type::BaseModel
              attr_accessor code: String

              attr_accessor runtime_context: Braintrust::FunctionReplaceParams::FunctionData::Code::Data::Inline::RuntimeContext

              attr_accessor type: Braintrust::FunctionReplaceParams::FunctionData::Code::Data::Inline::type_

              def initialize: (
                code: String,
                runtime_context: Braintrust::FunctionReplaceParams::FunctionData::Code::Data::Inline::RuntimeContext,
                type: Braintrust::FunctionReplaceParams::FunctionData::Code::Data::Inline::type_
              ) -> void

              type runtime_context =
                {
                  runtime: Braintrust::FunctionReplaceParams::FunctionData::Code::Data::Inline::RuntimeContext::runtime,
                  version: String
                }

              class RuntimeContext < Braintrust::Internal::Type::BaseModel
                attr_accessor runtime: Braintrust::FunctionReplaceParams::FunctionData::Code::Data::Inline::RuntimeContext::runtime

                attr_accessor version: String

                def initialize: (
                  runtime: Braintrust::FunctionReplaceParams::FunctionData::Code::Data::Inline::RuntimeContext::runtime,
                  version: String
                ) -> void

                type runtime = :node | :python

                module Runtime
                  extend Braintrust::Internal::Type::Enum

                  NODE: :node
                  PYTHON: :python

                  def self?.values: -> ::Array[Braintrust::FunctionReplaceParams::FunctionData::Code::Data::Inline::RuntimeContext::runtime]
                end
              end

              type type_ = :inline

              module Type
                extend Braintrust::Internal::Type::Enum

                INLINE: :inline

                def self?.values: -> ::Array[Braintrust::FunctionReplaceParams::FunctionData::Code::Data::Inline::type_]
              end
            end

            def self?.variants: -> ::Array[Braintrust::FunctionReplaceParams::FunctionData::Code::data]
          end

          type type_ = :code

          module Type
            extend Braintrust::Internal::Type::Enum

            CODE: :code

            def self?.values: -> ::Array[Braintrust::FunctionReplaceParams::FunctionData::Code::type_]
          end
        end

        type global =
          {
            name: String,
            type: Braintrust::FunctionReplaceParams::FunctionData::Global::type_
          }

        class Global < Braintrust::Internal::Type::BaseModel
          attr_accessor name: String

          attr_accessor type: Braintrust::FunctionReplaceParams::FunctionData::Global::type_

          def initialize: (
            name: String,
            type: Braintrust::FunctionReplaceParams::FunctionData::Global::type_
          ) -> void

          type type_ = :global

          module Type
            extend Braintrust::Internal::Type::Enum

            GLOBAL: :global

            def self?.values: -> ::Array[Braintrust::FunctionReplaceParams::FunctionData::Global::type_]
          end
        end

        def self?.variants: -> ::Array[Braintrust::Models::FunctionReplaceParams::function_data]
      end

      type function_schema = { parameters: top, returns: top }

      class FunctionSchema < Braintrust::Internal::Type::BaseModel
        attr_reader parameters: top?

        def parameters=: (top) -> top

        attr_reader returns: top?

        def returns=: (top) -> top

        def initialize: (?parameters: top, ?returns: top) -> void
      end

      type function_type = :llm | :scorer | :task | :tool

      module FunctionType
        extend Braintrust::Internal::Type::Enum

        LLM: :llm
        SCORER: :scorer
        TASK: :task
        TOOL: :tool

        def self?.values: -> ::Array[Braintrust::Models::FunctionReplaceParams::function_type]
      end

      type origin =
        {
          object_id_: String,
          object_type: Braintrust::Models::acl_object_type,
          internal: bool?
        }

      class Origin < Braintrust::Internal::Type::BaseModel
        attr_accessor object_id_: String

        attr_accessor object_type: Braintrust::Models::acl_object_type

        attr_accessor internal: bool?

        def initialize: (
          object_id_: String,
          object_type: Braintrust::Models::acl_object_type,
          ?internal: bool?
        ) -> void
      end
    end
  end
end
