module Braintrust
  module Models
    type function_replace_params =
      {
        function_data: Braintrust::Models::FunctionReplaceParams::function_data,
        name: String,
        project_id: String,
        slug: String,
        description: String?,
        function_schema: Braintrust::Models::FunctionReplaceParams::FunctionSchema?,
        function_type: Braintrust::Models::FunctionReplaceParams::function_type?,
        origin: Braintrust::Models::FunctionReplaceParams::Origin?,
        prompt_data: Braintrust::Models::PromptData?,
        tags: ::Array[String]?
      }
      & Braintrust::request_parameters

    class FunctionReplaceParams < Braintrust::BaseModel
      extend Braintrust::RequestParameters::Converter
      include Braintrust::RequestParameters

      attr_accessor function_data: Braintrust::Models::FunctionReplaceParams::function_data

      attr_accessor name: String

      attr_accessor project_id: String

      attr_accessor slug: String

      attr_accessor description: String?

      attr_accessor function_schema: Braintrust::Models::FunctionReplaceParams::FunctionSchema?

      attr_accessor function_type: Braintrust::Models::FunctionReplaceParams::function_type?

      attr_accessor origin: Braintrust::Models::FunctionReplaceParams::Origin?

      attr_accessor prompt_data: Braintrust::Models::PromptData?

      attr_accessor tags: ::Array[String]?

      def initialize:
        (
          function_data: Braintrust::Models::FunctionReplaceParams::function_data,
          name: String,
          project_id: String,
          slug: String,
          description: String?,
          function_schema: Braintrust::Models::FunctionReplaceParams::FunctionSchema?,
          function_type: Braintrust::Models::FunctionReplaceParams::function_type?,
          origin: Braintrust::Models::FunctionReplaceParams::Origin?,
          prompt_data: Braintrust::Models::PromptData?,
          tags: ::Array[String]?,
          request_options: Braintrust::request_opts
        ) -> void
        | (
          ?Braintrust::Models::function_replace_params
          | Braintrust::BaseModel data
        ) -> void

      def to_hash: -> Braintrust::Models::function_replace_params

      type function_data =
        Braintrust::Models::FunctionReplaceParams::FunctionData::Prompt
        | Braintrust::Models::FunctionReplaceParams::FunctionData::Code
        | Braintrust::Models::FunctionReplaceParams::FunctionData::Global

      class FunctionData < Braintrust::Union
        type prompt =
          {
            type: Braintrust::Models::FunctionReplaceParams::FunctionData::Prompt::type_
          }

        class Prompt < Braintrust::BaseModel
          attr_accessor type: Braintrust::Models::FunctionReplaceParams::FunctionData::Prompt::type_

          def initialize:
            (
              type: Braintrust::Models::FunctionReplaceParams::FunctionData::Prompt::type_
            ) -> void
            | (
              ?Braintrust::Models::FunctionReplaceParams::FunctionData::prompt
              | Braintrust::BaseModel data
            ) -> void

          def to_hash: -> Braintrust::Models::FunctionReplaceParams::FunctionData::prompt

          type type_ = :prompt

          class Type < Braintrust::Enum
            PROMPT: :prompt

            def self.values: -> ::Array[Braintrust::Models::FunctionReplaceParams::FunctionData::Prompt::type_]
          end
        end

        type code =
          {
            data: Braintrust::Models::FunctionReplaceParams::FunctionData::Code::data,
            type: Braintrust::Models::FunctionReplaceParams::FunctionData::Code::type_
          }

        class Code < Braintrust::BaseModel
          attr_accessor data: Braintrust::Models::FunctionReplaceParams::FunctionData::Code::data

          attr_accessor type: Braintrust::Models::FunctionReplaceParams::FunctionData::Code::type_

          def initialize:
            (
              data: Braintrust::Models::FunctionReplaceParams::FunctionData::Code::data,
              type: Braintrust::Models::FunctionReplaceParams::FunctionData::Code::type_
            ) -> void
            | (
              ?Braintrust::Models::FunctionReplaceParams::FunctionData::code
              | Braintrust::BaseModel data
            ) -> void

          def to_hash: -> Braintrust::Models::FunctionReplaceParams::FunctionData::code

          type data =
            Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Bundle
            | Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Inline

          class Data < Braintrust::Union
            type bundle =
              {
                type: Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Bundle::type_
              }

            class Bundle < Braintrust::Models::CodeBundle
              def `type`: -> Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Bundle::type_

              def type=: (
                Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Bundle::type_ _
              ) -> Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Bundle::type_

              def initialize:
                (
                  type: Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Bundle::type_
                ) -> void
                | (
                  ?Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::bundle
                  | Braintrust::BaseModel data
                ) -> void

              def to_hash: -> Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::bundle

              type type_ = :bundle

              class Type < Braintrust::Enum
                BUNDLE: :bundle

                def self.values: -> ::Array[Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Bundle::type_]
              end
            end

            type inline =
              {
                code: String,
                runtime_context: Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Inline::RuntimeContext,
                type: Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Inline::type_
              }

            class Inline < Braintrust::BaseModel
              attr_accessor code: String

              attr_accessor runtime_context: Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Inline::RuntimeContext

              attr_accessor type: Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Inline::type_

              def initialize:
                (
                  code: String,
                  runtime_context: Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Inline::RuntimeContext,
                  type: Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Inline::type_
                ) -> void
                | (
                  ?Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::inline
                  | Braintrust::BaseModel data
                ) -> void

              def to_hash: -> Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::inline

              type runtime_context =
                {
                  runtime: Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Inline::RuntimeContext::runtime,
                  version: String
                }

              class RuntimeContext < Braintrust::BaseModel
                attr_accessor runtime: Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Inline::RuntimeContext::runtime

                attr_accessor version: String

                def initialize:
                  (
                    runtime: Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Inline::RuntimeContext::runtime,
                    version: String
                  ) -> void
                  | (
                    ?Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Inline::runtime_context
                    | Braintrust::BaseModel data
                  ) -> void

                def to_hash: -> Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Inline::runtime_context

                type runtime = :node | :python

                class Runtime < Braintrust::Enum
                  NODE: :node
                  PYTHON: :python

                  def self.values: -> ::Array[Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Inline::RuntimeContext::runtime]
                end
              end

              type type_ = :inline

              class Type < Braintrust::Enum
                INLINE: :inline

                def self.values: -> ::Array[Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Inline::type_]
              end
            end

            def self.variants: -> [Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Bundle, Braintrust::Models::FunctionReplaceParams::FunctionData::Code::Data::Inline]
          end

          type type_ = :code

          class Type < Braintrust::Enum
            CODE: :code

            def self.values: -> ::Array[Braintrust::Models::FunctionReplaceParams::FunctionData::Code::type_]
          end
        end

        type global =
          {
            name: String,
            type: Braintrust::Models::FunctionReplaceParams::FunctionData::Global::type_
          }

        class Global < Braintrust::BaseModel
          attr_accessor name: String

          attr_accessor type: Braintrust::Models::FunctionReplaceParams::FunctionData::Global::type_

          def initialize:
            (
              name: String,
              type: Braintrust::Models::FunctionReplaceParams::FunctionData::Global::type_
            ) -> void
            | (
              ?Braintrust::Models::FunctionReplaceParams::FunctionData::global
              | Braintrust::BaseModel data
            ) -> void

          def to_hash: -> Braintrust::Models::FunctionReplaceParams::FunctionData::global

          type type_ = :global

          class Type < Braintrust::Enum
            GLOBAL: :global

            def self.values: -> ::Array[Braintrust::Models::FunctionReplaceParams::FunctionData::Global::type_]
          end
        end

        def self.variants: -> [Braintrust::Models::FunctionReplaceParams::FunctionData::Prompt, Braintrust::Models::FunctionReplaceParams::FunctionData::Code, Braintrust::Models::FunctionReplaceParams::FunctionData::Global]
      end

      type function_schema = { parameters: top, returns: top }

      class FunctionSchema < Braintrust::BaseModel
        attr_reader parameters: top?

        def parameters=: (top) -> top

        attr_reader returns: top?

        def returns=: (top) -> top

        def initialize:
          (parameters: top, returns: top) -> void
          | (
            ?Braintrust::Models::FunctionReplaceParams::function_schema
            | Braintrust::BaseModel data
          ) -> void

        def to_hash: -> Braintrust::Models::FunctionReplaceParams::function_schema
      end

      type function_type = :llm | :scorer | :task | :tool

      class FunctionType < Braintrust::Enum
        LLM: :llm
        SCORER: :scorer
        TASK: :task
        TOOL: :tool

        def self.values: -> ::Array[Braintrust::Models::FunctionReplaceParams::function_type]
      end

      type origin =
        {
          object_id_: String,
          object_type: Braintrust::Models::acl_object_type,
          internal: bool?
        }

      class Origin < Braintrust::BaseModel
        attr_accessor object_id_: String

        attr_accessor object_type: Braintrust::Models::acl_object_type

        attr_accessor internal: bool?

        def initialize:
          (
            object_id_: String,
            object_type: Braintrust::Models::acl_object_type,
            internal: bool?
          ) -> void
          | (
            ?Braintrust::Models::FunctionReplaceParams::origin
            | Braintrust::BaseModel data
          ) -> void

        def to_hash: -> Braintrust::Models::FunctionReplaceParams::origin
      end
    end
  end
end
