module Braintrust
  module Models
    type function_list_params =
      {
        ending_before: String,
        function_name: String,
        ids: Braintrust::Models::FunctionListParams::ids,
        limit: Integer?,
        org_name: String,
        project_id: String,
        project_name: String,
        slug: String,
        starting_after: String,
        version: String
      }
      & Braintrust::request_parameters

    class FunctionListParams < Braintrust::BaseModel
      extend Braintrust::Type::RequestParameters::Converter
      include Braintrust::RequestParameters

      attr_reader ending_before: String?

      def ending_before=: (String) -> String

      attr_reader function_name: String?

      def function_name=: (String) -> String

      attr_reader ids: Braintrust::Models::FunctionListParams::ids?

      def ids=: (
        Braintrust::Models::FunctionListParams::ids
      ) -> Braintrust::Models::FunctionListParams::ids

      attr_accessor limit: Integer?

      attr_reader org_name: String?

      def org_name=: (String) -> String

      attr_reader project_id: String?

      def project_id=: (String) -> String

      attr_reader project_name: String?

      def project_name=: (String) -> String

      attr_reader slug: String?

      def slug=: (String) -> String

      attr_reader starting_after: String?

      def starting_after=: (String) -> String

      attr_reader version: String?

      def version=: (String) -> String

      def initialize: (
        ?ending_before: String,
        ?function_name: String,
        ?ids: Braintrust::Models::FunctionListParams::ids,
        ?limit: Integer?,
        ?org_name: String,
        ?project_id: String,
        ?project_name: String,
        ?slug: String,
        ?starting_after: String,
        ?version: String,
        ?request_options: Braintrust::request_opts
      ) -> void

      def to_hash: -> Braintrust::Models::function_list_params

      type ids = String | ::Array[String]

      module IDs
        extend Braintrust::Union

        def self?.variants: -> [String, ::Array[String]]

        type string_array = ::Array[String]

        StringArray: string_array
      end
    end
  end
end
