module Braintrust
  module Models
    type online_score_config =
      {
        sampling_rate: Float,
        scorers: ::Array[Braintrust::Models::OnlineScoreConfig::scorer],
        apply_to_root_span: bool?,
        apply_to_span_names: ::Array[String]?
      }

    class OnlineScoreConfig < Braintrust::Internal::Type::BaseModel
      attr_accessor sampling_rate: Float

      attr_accessor scorers: ::Array[Braintrust::Models::OnlineScoreConfig::scorer]

      attr_accessor apply_to_root_span: bool?

      attr_accessor apply_to_span_names: ::Array[String]?

      def initialize: (
        sampling_rate: Float,
        scorers: ::Array[Braintrust::Models::OnlineScoreConfig::scorer],
        ?apply_to_root_span: bool?,
        ?apply_to_span_names: ::Array[String]?
      ) -> void

      def to_hash: -> {
        sampling_rate: Float,
        scorers: ::Array[Braintrust::Models::OnlineScoreConfig::scorer],
        apply_to_root_span: bool?,
        apply_to_span_names: ::Array[String]?
      }

      type scorer =
        Braintrust::OnlineScoreConfig::Scorer::Function
        | Braintrust::OnlineScoreConfig::Scorer::Global

      module Scorer
        extend Braintrust::Internal::Type::Union

        type function =
          {
            id: String,
            type: Braintrust::Models::OnlineScoreConfig::Scorer::Function::type_
          }

        class Function < Braintrust::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor type: Braintrust::Models::OnlineScoreConfig::Scorer::Function::type_

          def initialize: (
            id: String,
            type: Braintrust::Models::OnlineScoreConfig::Scorer::Function::type_
          ) -> void

          def to_hash: -> {
            id: String,
            type: Braintrust::Models::OnlineScoreConfig::Scorer::Function::type_
          }

          type type_ = :function

          module Type
            extend Braintrust::Internal::Type::Enum

            FUNCTION: :function

            def self?.values: -> ::Array[Braintrust::Models::OnlineScoreConfig::Scorer::Function::type_]
          end
        end

        type global =
          {
            name: String,
            type: Braintrust::Models::OnlineScoreConfig::Scorer::Global::type_
          }

        class Global < Braintrust::Internal::Type::BaseModel
          attr_accessor name: String

          attr_accessor type: Braintrust::Models::OnlineScoreConfig::Scorer::Global::type_

          def initialize: (
            name: String,
            type: Braintrust::Models::OnlineScoreConfig::Scorer::Global::type_
          ) -> void

          def to_hash: -> {
            name: String,
            type: Braintrust::Models::OnlineScoreConfig::Scorer::Global::type_
          }

          type type_ = :global

          module Type
            extend Braintrust::Internal::Type::Enum

            GLOBAL: :global

            def self?.values: -> ::Array[Braintrust::Models::OnlineScoreConfig::Scorer::Global::type_]
          end
        end

        def self?.variants: -> ::Array[Braintrust::Models::OnlineScoreConfig::scorer]
      end
    end
  end
end
