module Braintrust
  module Models
    type permission =
      :create
      | :read
      | :update
      | :delete
      | :create_acls
      | :read_acls
      | :update_acls
      | :delete_acls

    class Permission < Braintrust::Enum
      CREATE: :create
      READ: :read
      UPDATE: :update
      DELETE: :delete
      CREATE_ACLS: :create_acls
      READ_ACLS: :read_acls
      UPDATE_ACLS: :update_acls
      DELETE_ACLS: :delete_acls

      def self.values: -> ::Array[Braintrust::Models::permission]
    end
  end
end
