module Braintrust
  module Models
    type project_score_category = { name: String, value: Float }

    class ProjectScoreCategory < Braintrust::Internal::Type::BaseModel
      attr_accessor name: String

      attr_accessor value: Float

      def initialize: (name: String, value: Float) -> void
    end
  end
end
