module Braintrust
  module Models
    type project_tag_delete_params = {  } & Braintrust::request_parameters

    class ProjectTagDeleteParams < Braintrust::BaseModel
      extend Braintrust::RequestParameters::Converter
      include Braintrust::RequestParameters

      def initialize: (?request_options: Braintrust::request_opts) -> void

      def to_hash: -> Braintrust::Models::project_tag_delete_params
    end
  end
end
