module Braintrust
  module Models
    type project_score_config =
      {
        destination: String?,
        multi_select: bool?,
        online: Braintrust::Models::OnlineScoreConfig?
      }

    class ProjectScoreConfig < Braintrust::BaseModel
      attr_accessor destination: String?

      attr_accessor multi_select: bool?

      attr_accessor online: Braintrust::Models::OnlineScoreConfig?

      def initialize:
        (
          ?destination: String?,
          ?multi_select: bool?,
          ?online: Braintrust::Models::OnlineScoreConfig?
        ) -> void
        | (
          ?Braintrust::Models::project_score_config | Braintrust::BaseModel data
        ) -> void

      def to_hash: -> Braintrust::Models::project_score_config
    end
  end
end
