module Braintrust
  module Models
    type project_score_delete_params =
      {  } & Braintrust::Internal::Type::request_parameters

    class ProjectScoreDeleteParams < Braintrust::Internal::Type::BaseModel
      extend Braintrust::Internal::Type::RequestParameters::Converter
      include Braintrust::Internal::Type::RequestParameters

      def initialize: (?request_options: Braintrust::request_opts) -> void

      def to_hash: -> Braintrust::Models::project_score_delete_params
    end
  end
end
