module Braintrust
  module Models
    type project_score_update_params =
      {
        categories: Braintrust::Models::ProjectScoreUpdateParams::categories?,
        config: Braintrust::Models::ProjectScoreConfig?,
        description: String?,
        name: String?,
        score_type: Braintrust::Models::project_score_type?
      }
      & Braintrust::request_parameters

    class ProjectScoreUpdateParams < Braintrust::BaseModel
      extend Braintrust::RequestParameters::Converter
      include Braintrust::RequestParameters

      attr_accessor categories: Braintrust::Models::ProjectScoreUpdateParams::categories?

      attr_accessor config: Braintrust::Models::ProjectScoreConfig?

      attr_accessor description: String?

      attr_accessor name: String?

      attr_accessor score_type: Braintrust::Models::project_score_type?

      def initialize:
        (
          ?categories: Braintrust::Models::ProjectScoreUpdateParams::categories?,
          ?config: Braintrust::Models::ProjectScoreConfig?,
          ?description: String?,
          ?name: String?,
          ?score_type: Braintrust::Models::project_score_type?,
          ?request_options: Braintrust::request_opts
        ) -> void
        | (
          ?Braintrust::Models::project_score_update_params
          | Braintrust::BaseModel data
        ) -> void

      def to_hash: -> Braintrust::Models::project_score_update_params

      type categories =
        ::Array[Braintrust::Models::ProjectScoreCategory]
        | ::Hash[Symbol, Float]
        | ::Array[String]

      class Categories < Braintrust::Union
        type project_score_category_array =
          ::Array[Braintrust::Models::ProjectScoreCategory]

        ProjectScoreCategoryArray: project_score_category_array

        type float_map = ::Hash[Symbol, Float]

        FloatMap: float_map

        type string_array = ::Array[String]

        StringArray: string_array

        def self.variants: -> [::Array[Braintrust::Models::ProjectScoreCategory], ::Hash[Symbol, Float], ::Array[String]]
      end
    end
  end
end
