module Braintrust
  module Models
    type project_score_replace_params =
      {
        name: String,
        project_id: String,
        score_type: Braintrust::Models::project_score_type,
        categories: Braintrust::Models::ProjectScoreReplaceParams::categories?,
        config: Braintrust::Models::ProjectScoreConfig?,
        description: String?
      }
      & Braintrust::request_parameters

    class ProjectScoreReplaceParams < Braintrust::BaseModel
      extend Braintrust::RequestParameters::Converter
      include Braintrust::RequestParameters

      attr_accessor name: String

      attr_accessor project_id: String

      attr_accessor score_type: Braintrust::Models::project_score_type

      attr_accessor categories: Braintrust::Models::ProjectScoreReplaceParams::categories?

      attr_accessor config: Braintrust::Models::ProjectScoreConfig?

      attr_accessor description: String?

      def initialize:
        (
          name: String,
          project_id: String,
          score_type: Braintrust::Models::project_score_type,
          categories: Braintrust::Models::ProjectScoreReplaceParams::categories?,
          config: Braintrust::Models::ProjectScoreConfig?,
          description: String?,
          request_options: Braintrust::request_opts
        ) -> void
        | (
          ?Braintrust::Models::project_score_replace_params
          | Braintrust::BaseModel data
        ) -> void

      def to_hash: -> Braintrust::Models::project_score_replace_params

      type categories =
        ::Array[Braintrust::Models::ProjectScoreCategory]
        | ::Hash[Symbol, Float]
        | ::Array[String]

      class Categories < Braintrust::Union
        type project_score_category_array =
          ::Array[Braintrust::Models::ProjectScoreCategory]

        ProjectScoreCategoryArray: project_score_category_array

        type float_map = ::Hash[Symbol, Float]

        FloatMap: float_map

        type string_array = ::Array[String]

        StringArray: string_array

        def self.variants: -> [::Array[Braintrust::Models::ProjectScoreCategory], ::Hash[Symbol, Float], ::Array[String]]
      end
    end
  end
end
