module Braintrust
  module Models
    type project_tag_list_params =
      {
        ending_before: String,
        ids: Braintrust::Models::ProjectTagListParams::ids,
        limit: Integer?,
        org_name: String,
        project_id: String,
        project_name: String,
        project_tag_name: String,
        starting_after: String
      }
      & Braintrust::request_parameters

    class ProjectTagListParams < Braintrust::BaseModel
      extend Braintrust::RequestParameters::Converter
      include Braintrust::RequestParameters

      attr_reader ending_before: String?

      def ending_before=: (String) -> String

      attr_reader ids: Braintrust::Models::ProjectTagListParams::ids?

      def ids=: (
        Braintrust::Models::ProjectTagListParams::ids
      ) -> Braintrust::Models::ProjectTagListParams::ids

      attr_accessor limit: Integer?

      attr_reader org_name: String?

      def org_name=: (String) -> String

      attr_reader project_id: String?

      def project_id=: (String) -> String

      attr_reader project_name: String?

      def project_name=: (String) -> String

      attr_reader project_tag_name: String?

      def project_tag_name=: (String) -> String

      attr_reader starting_after: String?

      def starting_after=: (String) -> String

      def initialize: (
        ?ending_before: String,
        ?ids: Braintrust::Models::ProjectTagListParams::ids,
        ?limit: Integer?,
        ?org_name: String,
        ?project_id: String,
        ?project_name: String,
        ?project_tag_name: String,
        ?starting_after: String,
        ?request_options: Braintrust::request_opts
      ) -> void

      def to_hash: -> Braintrust::Models::project_tag_list_params

      type ids = String | ::Array[String]

      module IDs
        extend Braintrust::Union

        def self?.variants: -> [String, ::Array[String]]

        type string_array = ::Array[String]

        StringArray: string_array
      end
    end
  end
end
