module Braintrust
  module Models
    type project_score_type =
      :slider
      | :categorical
      | :weighted
      | :minimum
      | :maximum
      | :online
      | :"free-form"

    module ProjectScoreType
      extend Braintrust::Internal::Type::Enum

      SLIDER: :slider
      CATEGORICAL: :categorical
      WEIGHTED: :weighted
      MINIMUM: :minimum
      MAXIMUM: :maximum
      ONLINE: :online
      FREE_FORM: :"free-form"

      def self?.values: -> ::Array[Braintrust::Models::project_score_type]
    end
  end
end
