module Braintrust
  module Models
    type project_score_update_params =
      {
        categories: Braintrust::Models::ProjectScoreUpdateParams::categories?,
        config: Braintrust::Models::ProjectScoreConfig?,
        description: String?,
        name: String?,
        score_type: Braintrust::Models::project_score_type?
      }
      & Braintrust::Internal::Type::request_parameters

    class ProjectScoreUpdateParams < Braintrust::BaseModel
      extend Braintrust::Internal::Type::RequestParameters::Converter
      include Braintrust::Internal::Type::RequestParameters

      attr_accessor categories: Braintrust::Models::ProjectScoreUpdateParams::categories?

      attr_accessor config: Braintrust::Models::ProjectScoreConfig?

      attr_accessor description: String?

      attr_accessor name: String?

      attr_accessor score_type: Braintrust::Models::project_score_type?

      def initialize: (
        ?categories: Braintrust::Models::ProjectScoreUpdateParams::categories?,
        ?config: Braintrust::Models::ProjectScoreConfig?,
        ?description: String?,
        ?name: String?,
        ?score_type: Braintrust::Models::project_score_type?,
        ?request_options: Braintrust::request_opts
      ) -> void

      def to_hash: -> Braintrust::Models::project_score_update_params

      type categories =
        ::Array[Braintrust::Models::ProjectScoreCategory]
        | ::Hash[Symbol, Float]
        | ::Array[String]

      module Categories
        extend Braintrust::Union

        def self?.variants: -> [::Array[Braintrust::Models::ProjectScoreCategory], ::Hash[Symbol, Float], ::Array[String]]

        type project_score_category_array =
          ::Array[Braintrust::Models::ProjectScoreCategory]

        ProjectScoreCategoryArray: project_score_category_array

        type float_map = ::Hash[Symbol, Float]

        FloatMap: float_map

        type string_array = ::Array[String]

        StringArray: string_array
      end
    end
  end
end
