module Braintrust
  module Models
    type project_tag =
      {
        id: String,
        name: String,
        project_id: String,
        user_id: String,
        color: String?,
        created: Time?,
        description: String?
      }

    class ProjectTag < Braintrust::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor name: String

      attr_accessor project_id: String

      attr_accessor user_id: String

      attr_accessor color: String?

      attr_accessor created: Time?

      attr_accessor description: String?

      def initialize: (
        id: String,
        name: String,
        project_id: String,
        user_id: String,
        ?color: String?,
        ?created: Time?,
        ?description: String?
      ) -> void

      def to_hash: -> {
        id: String,
        name: String,
        project_id: String,
        user_id: String,
        color: String?,
        created: Time?,
        description: String?
      }
    end
  end
end
