module Braintrust
  module Models
    type project_tag_replace_params =
      { name: String, project_id: String, color: String?, description: String? }
      & Braintrust::Internal::Type::request_parameters

    class ProjectTagReplaceParams < Braintrust::Internal::Type::BaseModel
      extend Braintrust::Internal::Type::RequestParameters::Converter
      include Braintrust::Internal::Type::RequestParameters

      attr_accessor name: String

      attr_accessor project_id: String

      attr_accessor color: String?

      attr_accessor description: String?

      def initialize: (
        name: String,
        project_id: String,
        ?color: String?,
        ?description: String?,
        ?request_options: Braintrust::request_opts
      ) -> void

      def to_hash: -> Braintrust::Models::project_tag_replace_params
    end
  end
end
