module Braintrust
  module Models
    type project_score_create_params =
      {
        name: String,
        project_id: String,
        score_type: Braintrust::Models::ProjectScoreCreateParams::score_type,
        categories: Braintrust::Models::ProjectScoreCreateParams::categories?,
        config: Braintrust::Models::ProjectScoreConfig?,
        description: String?
      }
      & Braintrust::request_parameters

    class ProjectScoreCreateParams < Braintrust::BaseModel
      extend Braintrust::RequestParameters::Converter
      include Braintrust::RequestParameters

      attr_accessor name: String

      attr_accessor project_id: String

      attr_accessor score_type: Braintrust::Models::ProjectScoreCreateParams::score_type

      attr_accessor categories: Braintrust::Models::ProjectScoreCreateParams::categories?

      attr_accessor config: Braintrust::Models::ProjectScoreConfig?

      attr_accessor description: String?

      def initialize:
        (
          name: String,
          project_id: String,
          score_type: Braintrust::Models::ProjectScoreCreateParams::score_type,
          categories: Braintrust::Models::ProjectScoreCreateParams::categories?,
          config: Braintrust::Models::ProjectScoreConfig?,
          description: String?,
          request_options: Braintrust::request_opts
        ) -> void
        | (
          ?Braintrust::Models::project_score_create_params
          | Braintrust::BaseModel data
        ) -> void

      def to_hash: -> Braintrust::Models::project_score_create_params

      type score_type =
        :slider
        | :categorical
        | :weighted
        | :minimum
        | :maximum
        | :online
        | :"free-form"

      class ScoreType < Braintrust::Enum
        SLIDER: :slider
        CATEGORICAL: :categorical
        WEIGHTED: :weighted
        MINIMUM: :minimum
        MAXIMUM: :maximum
        ONLINE: :online
        FREE_FORM: :"free-form"

        def self.values: -> ::Array[Braintrust::Models::ProjectScoreCreateParams::score_type]
      end

      type categories =
        ::Array[Braintrust::Models::ProjectScoreCategory]
        | ::Hash[Symbol, Float]
        | ::Array[String]

      class Categories < Braintrust::Union
        type project_score_category_array =
          ::Array[Braintrust::Models::ProjectScoreCategory]

        ProjectScoreCategoryArray: project_score_category_array

        type float_map = ::Hash[Symbol, Float]

        FloatMap: float_map

        type string_array = ::Array[String]

        StringArray: string_array

        private def self.variants: -> [[nil, ::Array[Braintrust::Models::ProjectScoreCategory]], [nil, ::Hash[Symbol, Float]], [nil, ::Array[String]]]
      end
    end
  end
end
