module Braintrust
  module Models
    type project_tag_retrieve_params = {  } & Braintrust::request_parameters

    class ProjectTagRetrieveParams < Braintrust::BaseModel
      extend Braintrust::RequestParameters::Converter
      include Braintrust::RequestParameters

      def initialize:
        (?request_options: Braintrust::request_opts) -> void
        | (
          ?Braintrust::Models::project_tag_retrieve_params
          | Braintrust::BaseModel data
        ) -> void

      def to_hash: -> Braintrust::Models::project_tag_retrieve_params
    end
  end
end
