module Braintrust
  module Models
    type prompt_update_params =
      {
        description: String?,
        name: String?,
        prompt_data: Braintrust::Models::PromptData?,
        slug: String?,
        tags: ::Array[String]?
      }
      & Braintrust::request_parameters

    class PromptUpdateParams < Braintrust::BaseModel
      extend Braintrust::RequestParameters::Converter
      include Braintrust::RequestParameters

      attr_accessor description: String?

      attr_accessor name: String?

      attr_accessor prompt_data: Braintrust::Models::PromptData?

      attr_accessor slug: String?

      attr_accessor tags: ::Array[String]?

      def initialize:
        (
          description: String?,
          name: String?,
          prompt_data: Braintrust::Models::PromptData?,
          slug: String?,
          tags: ::Array[String]?,
          request_options: Braintrust::request_opts
        ) -> void
        | (
          ?Braintrust::Models::prompt_update_params | Braintrust::BaseModel data
        ) -> void

      def to_hash: -> Braintrust::Models::prompt_update_params
    end
  end
end
