module Braintrust
  module Models
    type prompt_data =
      {
        options: Braintrust::Models::PromptOptions?,
        origin: Braintrust::Models::PromptData::Origin?,
        parser: Braintrust::Models::PromptData::Parser?,
        prompt: Braintrust::Models::PromptData::prompt?,
        tool_functions: ::Array[Braintrust::Models::PromptData::tool_function]?
      }

    class PromptData < Braintrust::Internal::Type::BaseModel
      attr_accessor options: Braintrust::Models::PromptOptions?

      attr_accessor origin: Braintrust::Models::PromptData::Origin?

      attr_accessor parser: Braintrust::Models::PromptData::Parser?

      attr_accessor prompt: Braintrust::Models::PromptData::prompt?

      attr_accessor tool_functions: ::Array[Braintrust::Models::PromptData::tool_function]?

      def initialize: (
        ?options: Braintrust::Models::PromptOptions?,
        ?origin: Braintrust::Models::PromptData::Origin?,
        ?parser: Braintrust::Models::PromptData::Parser?,
        ?prompt: Braintrust::Models::PromptData::prompt?,
        ?tool_functions: ::Array[Braintrust::Models::PromptData::tool_function]?
      ) -> void

      def to_hash: -> Braintrust::Models::prompt_data

      type origin =
        { project_id: String, prompt_id: String, prompt_version: String }

      class Origin < Braintrust::Internal::Type::BaseModel
        attr_reader project_id: String?

        def project_id=: (String) -> String

        attr_reader prompt_id: String?

        def prompt_id=: (String) -> String

        attr_reader prompt_version: String?

        def prompt_version=: (String) -> String

        def initialize: (
          ?project_id: String,
          ?prompt_id: String,
          ?prompt_version: String
        ) -> void

        def to_hash: -> Braintrust::Models::PromptData::origin
      end

      type parser =
        {
          choice_scores: ::Hash[Symbol, Float],
          type: Braintrust::Models::PromptData::Parser::type_,
          use_cot: bool
        }

      class Parser < Braintrust::Internal::Type::BaseModel
        attr_accessor choice_scores: ::Hash[Symbol, Float]

        attr_accessor type: Braintrust::Models::PromptData::Parser::type_

        attr_accessor use_cot: bool

        def initialize: (
          choice_scores: ::Hash[Symbol, Float],
          type: Braintrust::Models::PromptData::Parser::type_,
          use_cot: bool
        ) -> void

        def to_hash: -> Braintrust::Models::PromptData::parser

        type type_ = :llm_classifier

        module Type
          extend Braintrust::Internal::Type::Enum

          LLM_CLASSIFIER: :llm_classifier

          def self?.values: -> ::Array[Braintrust::Models::PromptData::Parser::type_]
        end
      end

      type prompt =
        Braintrust::Models::PromptData::Prompt::Completion
        | Braintrust::Models::PromptData::Prompt::Chat

      module Prompt
        extend Braintrust::Internal::Type::Union

        type completion =
          {
            content: String,
            type: Braintrust::Models::PromptData::Prompt::Completion::type_
          }

        class Completion < Braintrust::Internal::Type::BaseModel
          attr_accessor content: String

          attr_accessor type: Braintrust::Models::PromptData::Prompt::Completion::type_

          def initialize: (
            content: String,
            type: Braintrust::Models::PromptData::Prompt::Completion::type_
          ) -> void

          def to_hash: -> Braintrust::Models::PromptData::Prompt::completion

          type type_ = :completion

          module Type
            extend Braintrust::Internal::Type::Enum

            COMPLETION: :completion

            def self?.values: -> ::Array[Braintrust::Models::PromptData::Prompt::Completion::type_]
          end
        end

        type chat =
          {
            messages: ::Array[Braintrust::Models::PromptData::Prompt::Chat::message],
            type: Braintrust::Models::PromptData::Prompt::Chat::type_,
            tools: String
          }

        class Chat < Braintrust::Internal::Type::BaseModel
          attr_accessor messages: ::Array[Braintrust::Models::PromptData::Prompt::Chat::message]

          attr_accessor type: Braintrust::Models::PromptData::Prompt::Chat::type_

          attr_reader tools: String?

          def tools=: (String) -> String

          def initialize: (
            messages: ::Array[Braintrust::Models::PromptData::Prompt::Chat::message],
            type: Braintrust::Models::PromptData::Prompt::Chat::type_,
            ?tools: String
          ) -> void

          def to_hash: -> Braintrust::Models::PromptData::Prompt::chat

          type message =
            Braintrust::Models::PromptData::Prompt::Chat::Message::System
            | Braintrust::Models::PromptData::Prompt::Chat::Message::User
            | Braintrust::Models::PromptData::Prompt::Chat::Message::Assistant
            | Braintrust::Models::PromptData::Prompt::Chat::Message::Tool
            | Braintrust::Models::PromptData::Prompt::Chat::Message::Function
            | Braintrust::Models::PromptData::Prompt::Chat::Message::Fallback

          module Message
            extend Braintrust::Internal::Type::Union

            type system_ =
              {
                role: Braintrust::Models::PromptData::Prompt::Chat::Message::System::role,
                content: String,
                name: String
              }

            class System < Braintrust::Internal::Type::BaseModel
              attr_accessor role: Braintrust::Models::PromptData::Prompt::Chat::Message::System::role

              attr_reader content: String?

              def content=: (String) -> String

              attr_reader name: String?

              def name=: (String) -> String

              def initialize: (
                role: Braintrust::Models::PromptData::Prompt::Chat::Message::System::role,
                ?content: String,
                ?name: String
              ) -> void

              def to_hash: -> Braintrust::Models::PromptData::Prompt::Chat::Message::system_

              type role = :system

              module Role
                extend Braintrust::Internal::Type::Enum

                SYSTEM: :system

                def self?.values: -> ::Array[Braintrust::Models::PromptData::Prompt::Chat::Message::System::role]
              end
            end

            type user =
              {
                role: Braintrust::Models::PromptData::Prompt::Chat::Message::User::role,
                content: Braintrust::Models::PromptData::Prompt::Chat::Message::User::content,
                name: String
              }

            class User < Braintrust::Internal::Type::BaseModel
              attr_accessor role: Braintrust::Models::PromptData::Prompt::Chat::Message::User::role

              attr_reader content: Braintrust::Models::PromptData::Prompt::Chat::Message::User::content?

              def content=: (
                Braintrust::Models::PromptData::Prompt::Chat::Message::User::content
              ) -> Braintrust::Models::PromptData::Prompt::Chat::Message::User::content

              attr_reader name: String?

              def name=: (String) -> String

              def initialize: (
                role: Braintrust::Models::PromptData::Prompt::Chat::Message::User::role,
                ?content: Braintrust::Models::PromptData::Prompt::Chat::Message::User::content,
                ?name: String
              ) -> void

              def to_hash: -> Braintrust::Models::PromptData::Prompt::Chat::Message::user

              type role = :user

              module Role
                extend Braintrust::Internal::Type::Enum

                USER: :user

                def self?.values: -> ::Array[Braintrust::Models::PromptData::Prompt::Chat::Message::User::role]
              end

              type content =
                String
                | ::Array[Braintrust::Models::PromptData::Prompt::Chat::Message::User::Content::array]

              module Content
                extend Braintrust::Internal::Type::Union

                type array =
                  Braintrust::Models::ChatCompletionContentPartText
                  | Braintrust::Models::ChatCompletionContentPartImage

                module Array
                  extend Braintrust::Internal::Type::Union

                  def self?.variants: -> [Braintrust::Models::ChatCompletionContentPartText, Braintrust::Models::ChatCompletionContentPartImage]
                end

                def self?.variants: -> [String, ::Array[Braintrust::Models::PromptData::Prompt::Chat::Message::User::Content::array]]

                type nested2_d_array =
                  ::Array[Braintrust::Models::PromptData::Prompt::Chat::Message::User::Content::array]

                Nested2DArray: nested2_d_array
              end
            end

            type assistant =
              {
                role: Braintrust::Models::PromptData::Prompt::Chat::Message::Assistant::role,
                content: String?,
                function_call: Braintrust::Models::PromptData::Prompt::Chat::Message::Assistant::FunctionCall?,
                name: String?,
                tool_calls: ::Array[Braintrust::Models::ChatCompletionMessageToolCall]?
              }

            class Assistant < Braintrust::Internal::Type::BaseModel
              attr_accessor role: Braintrust::Models::PromptData::Prompt::Chat::Message::Assistant::role

              attr_accessor content: String?

              attr_accessor function_call: Braintrust::Models::PromptData::Prompt::Chat::Message::Assistant::FunctionCall?

              attr_accessor name: String?

              attr_accessor tool_calls: ::Array[Braintrust::Models::ChatCompletionMessageToolCall]?

              def initialize: (
                role: Braintrust::Models::PromptData::Prompt::Chat::Message::Assistant::role,
                ?content: String?,
                ?function_call: Braintrust::Models::PromptData::Prompt::Chat::Message::Assistant::FunctionCall?,
                ?name: String?,
                ?tool_calls: ::Array[Braintrust::Models::ChatCompletionMessageToolCall]?
              ) -> void

              def to_hash: -> Braintrust::Models::PromptData::Prompt::Chat::Message::assistant

              type role = :assistant

              module Role
                extend Braintrust::Internal::Type::Enum

                ASSISTANT: :assistant

                def self?.values: -> ::Array[Braintrust::Models::PromptData::Prompt::Chat::Message::Assistant::role]
              end

              type function_call = { arguments: String, name: String }

              class FunctionCall < Braintrust::Internal::Type::BaseModel
                attr_accessor arguments: String

                attr_accessor name: String

                def initialize: (arguments: String, name: String) -> void

                def to_hash: -> Braintrust::Models::PromptData::Prompt::Chat::Message::Assistant::function_call
              end
            end

            type tool =
              {
                role: Braintrust::Models::PromptData::Prompt::Chat::Message::Tool::role,
                content: String,
                tool_call_id: String
              }

            class Tool < Braintrust::Internal::Type::BaseModel
              attr_accessor role: Braintrust::Models::PromptData::Prompt::Chat::Message::Tool::role

              attr_reader content: String?

              def content=: (String) -> String

              attr_reader tool_call_id: String?

              def tool_call_id=: (String) -> String

              def initialize: (
                role: Braintrust::Models::PromptData::Prompt::Chat::Message::Tool::role,
                ?content: String,
                ?tool_call_id: String
              ) -> void

              def to_hash: -> Braintrust::Models::PromptData::Prompt::Chat::Message::tool

              type role = :tool

              module Role
                extend Braintrust::Internal::Type::Enum

                TOOL: :tool

                def self?.values: -> ::Array[Braintrust::Models::PromptData::Prompt::Chat::Message::Tool::role]
              end
            end

            type function =
              {
                name: String,
                role: Braintrust::Models::PromptData::Prompt::Chat::Message::Function::role,
                content: String
              }

            class Function < Braintrust::Internal::Type::BaseModel
              attr_accessor name: String

              attr_accessor role: Braintrust::Models::PromptData::Prompt::Chat::Message::Function::role

              attr_reader content: String?

              def content=: (String) -> String

              def initialize: (
                name: String,
                role: Braintrust::Models::PromptData::Prompt::Chat::Message::Function::role,
                ?content: String
              ) -> void

              def to_hash: -> Braintrust::Models::PromptData::Prompt::Chat::Message::function

              type role = :function

              module Role
                extend Braintrust::Internal::Type::Enum

                FUNCTION: :function

                def self?.values: -> ::Array[Braintrust::Models::PromptData::Prompt::Chat::Message::Function::role]
              end
            end

            type fallback =
              {
                role: Braintrust::Models::PromptData::Prompt::Chat::Message::Fallback::role,
                content: String?
              }

            class Fallback < Braintrust::Internal::Type::BaseModel
              attr_accessor role: Braintrust::Models::PromptData::Prompt::Chat::Message::Fallback::role

              attr_accessor content: String?

              def initialize: (
                role: Braintrust::Models::PromptData::Prompt::Chat::Message::Fallback::role,
                ?content: String?
              ) -> void

              def to_hash: -> Braintrust::Models::PromptData::Prompt::Chat::Message::fallback

              type role = :model

              module Role
                extend Braintrust::Internal::Type::Enum

                MODEL: :model

                def self?.values: -> ::Array[Braintrust::Models::PromptData::Prompt::Chat::Message::Fallback::role]
              end
            end

            def self?.variants: -> [Braintrust::Models::PromptData::Prompt::Chat::Message::System, Braintrust::Models::PromptData::Prompt::Chat::Message::User, Braintrust::Models::PromptData::Prompt::Chat::Message::Assistant, Braintrust::Models::PromptData::Prompt::Chat::Message::Tool, Braintrust::Models::PromptData::Prompt::Chat::Message::Function, Braintrust::Models::PromptData::Prompt::Chat::Message::Fallback]
          end

          type type_ = :chat

          module Type
            extend Braintrust::Internal::Type::Enum

            CHAT: :chat

            def self?.values: -> ::Array[Braintrust::Models::PromptData::Prompt::Chat::type_]
          end
        end

        def self?.variants: -> [Braintrust::Models::PromptData::Prompt::Completion, Braintrust::Models::PromptData::Prompt::Chat]
      end

      type tool_function =
        Braintrust::Models::PromptData::ToolFunction::Function
        | Braintrust::Models::PromptData::ToolFunction::Global

      module ToolFunction
        extend Braintrust::Internal::Type::Union

        type function =
          {
            id: String,
            type: Braintrust::Models::PromptData::ToolFunction::Function::type_
          }

        class Function < Braintrust::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor type: Braintrust::Models::PromptData::ToolFunction::Function::type_

          def initialize: (
            id: String,
            type: Braintrust::Models::PromptData::ToolFunction::Function::type_
          ) -> void

          def to_hash: -> Braintrust::Models::PromptData::ToolFunction::function

          type type_ = :function

          module Type
            extend Braintrust::Internal::Type::Enum

            FUNCTION: :function

            def self?.values: -> ::Array[Braintrust::Models::PromptData::ToolFunction::Function::type_]
          end
        end

        type global =
          {
            name: String,
            type: Braintrust::Models::PromptData::ToolFunction::Global::type_
          }

        class Global < Braintrust::Internal::Type::BaseModel
          attr_accessor name: String

          attr_accessor type: Braintrust::Models::PromptData::ToolFunction::Global::type_

          def initialize: (
            name: String,
            type: Braintrust::Models::PromptData::ToolFunction::Global::type_
          ) -> void

          def to_hash: -> Braintrust::Models::PromptData::ToolFunction::global

          type type_ = :global

          module Type
            extend Braintrust::Internal::Type::Enum

            GLOBAL: :global

            def self?.values: -> ::Array[Braintrust::Models::PromptData::ToolFunction::Global::type_]
          end
        end

        def self?.variants: -> [Braintrust::Models::PromptData::ToolFunction::Function, Braintrust::Models::PromptData::ToolFunction::Global]
      end
    end
  end
end
