module Braintrust
  module Models
    type role_update_params =
      {
        add_member_permissions: ::Array[Braintrust::Models::RoleUpdateParams::AddMemberPermission]?,
        add_member_roles: ::Array[String]?,
        description: String?,
        name: String?,
        remove_member_permissions: ::Array[Braintrust::Models::RoleUpdateParams::RemoveMemberPermission]?,
        remove_member_roles: ::Array[String]?
      }
      & Braintrust::request_parameters

    class RoleUpdateParams < Braintrust::BaseModel
      extend Braintrust::Type::RequestParameters::Converter
      include Braintrust::RequestParameters

      attr_accessor add_member_permissions: ::Array[Braintrust::Models::RoleUpdateParams::AddMemberPermission]?

      attr_accessor add_member_roles: ::Array[String]?

      attr_accessor description: String?

      attr_accessor name: String?

      attr_accessor remove_member_permissions: ::Array[Braintrust::Models::RoleUpdateParams::RemoveMemberPermission]?

      attr_accessor remove_member_roles: ::Array[String]?

      def initialize: (
        ?add_member_permissions: ::Array[Braintrust::Models::RoleUpdateParams::AddMemberPermission]?,
        ?add_member_roles: ::Array[String]?,
        ?description: String?,
        ?name: String?,
        ?remove_member_permissions: ::Array[Braintrust::Models::RoleUpdateParams::RemoveMemberPermission]?,
        ?remove_member_roles: ::Array[String]?,
        ?request_options: Braintrust::request_opts
      ) -> void

      def to_hash: -> Braintrust::Models::role_update_params

      type add_member_permission =
        {
          permission: Braintrust::Models::permission,
          restrict_object_type: Braintrust::Models::acl_object_type?
        }

      class AddMemberPermission < Braintrust::BaseModel
        attr_accessor permission: Braintrust::Models::permission

        attr_accessor restrict_object_type: Braintrust::Models::acl_object_type?

        def initialize: (
          permission: Braintrust::Models::permission,
          ?restrict_object_type: Braintrust::Models::acl_object_type?
        ) -> void

        def to_hash: -> Braintrust::Models::RoleUpdateParams::add_member_permission
      end

      type remove_member_permission =
        {
          permission: Braintrust::Models::permission,
          restrict_object_type: Braintrust::Models::acl_object_type?
        }

      class RemoveMemberPermission < Braintrust::BaseModel
        attr_accessor permission: Braintrust::Models::permission

        attr_accessor restrict_object_type: Braintrust::Models::acl_object_type?

        def initialize: (
          permission: Braintrust::Models::permission,
          ?restrict_object_type: Braintrust::Models::acl_object_type?
        ) -> void

        def to_hash: -> Braintrust::Models::RoleUpdateParams::remove_member_permission
      end
    end
  end
end
