module Braintrust
  module Models
    type role_retrieve_params = {  } & Braintrust::request_parameters

    class RoleRetrieveParams < Braintrust::BaseModel
      extend Braintrust::Type::RequestParameters::Converter
      include Braintrust::RequestParameters

      def initialize: (?request_options: Braintrust::request_opts) -> void

      def to_hash: -> Braintrust::Models::role_retrieve_params
    end
  end
end
