module Braintrust
  module Models
    type role_replace_params =
      {
        name: String,
        description: String?,
        member_permissions: ::Array[Braintrust::Models::RoleReplaceParams::MemberPermission]?,
        member_roles: ::Array[String]?,
        org_name: String?
      }
      & Braintrust::request_parameters

    class RoleReplaceParams < Braintrust::BaseModel
      extend Braintrust::RequestParameters::Converter
      include Braintrust::RequestParameters

      attr_accessor name: String

      attr_accessor description: String?

      attr_accessor member_permissions: ::Array[Braintrust::Models::RoleReplaceParams::MemberPermission]?

      attr_accessor member_roles: ::Array[String]?

      attr_accessor org_name: String?

      def initialize:
        (
          name: String,
          description: String?,
          member_permissions: ::Array[Braintrust::Models::RoleReplaceParams::MemberPermission]?,
          member_roles: ::Array[String]?,
          org_name: String?,
          request_options: Braintrust::request_opts
        ) -> void
        | (
          ?Braintrust::Models::role_replace_params | Braintrust::BaseModel data
        ) -> void

      def to_hash: -> Braintrust::Models::role_replace_params

      type member_permission =
        {
          permission: Braintrust::Models::RoleReplaceParams::MemberPermission::permission,
          restrict_object_type: Braintrust::Models::RoleReplaceParams::MemberPermission::restrict_object_type?
        }

      class MemberPermission < Braintrust::BaseModel
        attr_accessor permission: Braintrust::Models::RoleReplaceParams::MemberPermission::permission

        attr_accessor restrict_object_type: Braintrust::Models::RoleReplaceParams::MemberPermission::restrict_object_type?

        def initialize:
          (
            permission: Braintrust::Models::RoleReplaceParams::MemberPermission::permission,
            restrict_object_type: Braintrust::Models::RoleReplaceParams::MemberPermission::restrict_object_type?
          ) -> void
          | (
            ?Braintrust::Models::RoleReplaceParams::member_permission
            | Braintrust::BaseModel data
          ) -> void

        def to_hash: -> Braintrust::Models::RoleReplaceParams::member_permission

        type permission =
          :create
          | :read
          | :update
          | :delete
          | :create_acls
          | :read_acls
          | :update_acls
          | :delete_acls

        class Permission < Braintrust::Enum
          CREATE: :create
          READ: :read
          UPDATE: :update
          DELETE: :delete
          CREATE_ACLS: :create_acls
          READ_ACLS: :read_acls
          UPDATE_ACLS: :update_acls
          DELETE_ACLS: :delete_acls

          def self.values: -> ::Array[Braintrust::Models::RoleReplaceParams::MemberPermission::permission]
        end

        type restrict_object_type =
          :organization
          | :project
          | :experiment
          | :dataset
          | :prompt
          | :prompt_session
          | :group
          | :role
          | :org_member
          | :project_log
          | :org_project

        class RestrictObjectType < Braintrust::Enum
          ORGANIZATION: :organization
          PROJECT: :project
          EXPERIMENT: :experiment
          DATASET: :dataset
          PROMPT: :prompt
          PROMPT_SESSION: :prompt_session
          GROUP: :group
          ROLE: :role
          ORG_MEMBER: :org_member
          PROJECT_LOG: :project_log
          ORG_PROJECT: :org_project

          def self.values: -> ::Array[Braintrust::Models::RoleReplaceParams::MemberPermission::restrict_object_type]
        end
      end
    end
  end
end
