module Braintrust
  module Models
    type role_replace_params =
      {
        name: String,
        description: String?,
        member_permissions: ::Array[Braintrust::Models::RoleReplaceParams::MemberPermission]?,
        member_roles: ::Array[String]?,
        org_name: String?
      }
      & Braintrust::Internal::Type::request_parameters

    class RoleReplaceParams < Braintrust::Internal::Type::BaseModel
      extend Braintrust::Internal::Type::RequestParameters::Converter
      include Braintrust::Internal::Type::RequestParameters

      attr_accessor name: String

      attr_accessor description: String?

      attr_accessor member_permissions: ::Array[Braintrust::Models::RoleReplaceParams::MemberPermission]?

      attr_accessor member_roles: ::Array[String]?

      attr_accessor org_name: String?

      def initialize: (
        name: String,
        ?description: String?,
        ?member_permissions: ::Array[Braintrust::Models::RoleReplaceParams::MemberPermission]?,
        ?member_roles: ::Array[String]?,
        ?org_name: String?,
        ?request_options: Braintrust::request_opts
      ) -> void

      def to_hash: -> Braintrust::Models::role_replace_params

      type member_permission =
        {
          permission: Braintrust::Models::permission,
          restrict_object_type: Braintrust::Models::acl_object_type?
        }

      class MemberPermission < Braintrust::Internal::Type::BaseModel
        attr_accessor permission: Braintrust::Models::permission

        attr_accessor restrict_object_type: Braintrust::Models::acl_object_type?

        def initialize: (
          permission: Braintrust::Models::permission,
          ?restrict_object_type: Braintrust::Models::acl_object_type?
        ) -> void

        def to_hash: -> Braintrust::Models::RoleReplaceParams::member_permission
      end
    end
  end
end
