module Braintrust
  module Models
    type role_delete_params =
      {  } & Braintrust::Internal::Type::request_parameters

    class RoleDeleteParams < Braintrust::Internal::Type::BaseModel
      extend Braintrust::Internal::Type::RequestParameters::Converter
      include Braintrust::Internal::Type::RequestParameters

      def initialize: (?request_options: Braintrust::request_opts) -> void

      def to_hash: -> Braintrust::Models::role_delete_params
    end
  end
end
