module Braintrust
  module Models
    type span_attributes =
      { name: String?, type: Braintrust::Models::span_type? }

    class SpanAttributes < Braintrust::BaseModel
      attr_accessor name: String?

      attr_accessor type: Braintrust::Models::span_type?

      def initialize: (
        ?name: String?,
        ?type: Braintrust::Models::span_type?
      ) -> void

      def to_hash: -> Braintrust::Models::span_attributes
    end
  end
end
