module Braintrust
  module Models
    type span_iframe_create_params =
      {
        name: String,
        project_id: String,
        url: String,
        description: String?,
        post_message: bool?
      }
      & Braintrust::Internal::Type::request_parameters

    class SpanIframeCreateParams < Braintrust::Internal::Type::BaseModel
      extend Braintrust::Internal::Type::RequestParameters::Converter
      include Braintrust::Internal::Type::RequestParameters

      attr_accessor name: String

      attr_accessor project_id: String

      attr_accessor url: String

      attr_accessor description: String?

      attr_accessor post_message: bool?

      def initialize: (
        name: String,
        project_id: String,
        url: String,
        ?description: String?,
        ?post_message: bool?,
        ?request_options: Braintrust::request_opts
      ) -> void

      def to_hash: -> {
        name: String,
        project_id: String,
        url: String,
        description: String?,
        post_message: bool?,
        request_options: Braintrust::RequestOptions
      }
    end
  end
end
