module Braintrust
  module Models
    type span_type = :llm | :score | :function | :eval | :task | :tool

    class SpanType < Braintrust::Enum
      LLM: :llm
      SCORE: :score
      FUNCTION: :function
      EVAL: :eval
      TASK: :task
      TOOL: :tool

      def self.values: -> ::Array[Braintrust::Models::span_type]
    end
  end
end
