module Braintrust
  module Models
    type span_iframe_delete_params = {  } & Braintrust::request_parameters

    class SpanIframeDeleteParams < Braintrust::BaseModel
      extend Braintrust::RequestParameters::Converter
      include Braintrust::RequestParameters

      def initialize: (?request_options: Braintrust::request_opts) -> void

      def to_hash: -> Braintrust::Models::span_iframe_delete_params
    end
  end
end
