module Braintrust
  module Models
    type top_level_hello_world_params =
      {  } & Braintrust::Internal::Type::request_parameters

    class TopLevelHelloWorldParams < Braintrust::BaseModel
      extend Braintrust::Internal::Type::RequestParameters::Converter
      include Braintrust::Internal::Type::RequestParameters

      def initialize: (?request_options: Braintrust::request_opts) -> void

      def to_hash: -> Braintrust::Models::top_level_hello_world_params
    end
  end
end
