module Braintrust
  module Models
    type user =
      {
        id: String,
        avatar_url: String?,
        created: Time?,
        email: String?,
        family_name: String?,
        given_name: String?
      }

    class User < Braintrust::BaseModel
      attr_accessor id: String

      attr_accessor avatar_url: String?

      attr_accessor created: Time?

      attr_accessor email: String?

      attr_accessor family_name: String?

      attr_accessor given_name: String?

      def initialize: (
        id: String,
        ?avatar_url: String?,
        ?created: Time?,
        ?email: String?,
        ?family_name: String?,
        ?given_name: String?
      ) -> void

      def to_hash: -> Braintrust::Models::user
    end
  end
end
