module Braintrust
  module Models
    type view_update_params =
      {
        object_id_: String,
        object_type: Braintrust::Models::acl_object_type,
        name: String?,
        options: Braintrust::Models::ViewOptions?,
        user_id: String?,
        view_data: Braintrust::Models::ViewData?,
        view_type: Braintrust::Models::ViewUpdateParams::view_type?
      }
      & Braintrust::request_parameters

    class ViewUpdateParams < Braintrust::BaseModel
      extend Braintrust::Type::RequestParameters::Converter
      include Braintrust::RequestParameters

      attr_accessor object_id_: String

      attr_accessor object_type: Braintrust::Models::acl_object_type

      attr_accessor name: String?

      attr_accessor options: Braintrust::Models::ViewOptions?

      attr_accessor user_id: String?

      attr_accessor view_data: Braintrust::Models::ViewData?

      attr_accessor view_type: Braintrust::Models::ViewUpdateParams::view_type?

      def initialize: (
        object_id_: String,
        object_type: Braintrust::Models::acl_object_type,
        ?name: String?,
        ?options: Braintrust::Models::ViewOptions?,
        ?user_id: String?,
        ?view_data: Braintrust::Models::ViewData?,
        ?view_type: Braintrust::Models::ViewUpdateParams::view_type?,
        ?request_options: Braintrust::request_opts
      ) -> void

      def to_hash: -> Braintrust::Models::view_update_params

      type view_type =
        :projects
        | :experiments
        | :experiment
        | :playgrounds
        | :playground
        | :datasets
        | :dataset
        | :prompts
        | :tools
        | :scorers
        | :logs

      module ViewType
        extend Braintrust::Enum

        PROJECTS: :projects
        EXPERIMENTS: :experiments
        EXPERIMENT: :experiment
        PLAYGROUNDS: :playgrounds
        PLAYGROUND: :playground
        DATASETS: :datasets
        DATASET: :dataset
        PROMPTS: :prompts
        TOOLS: :tools
        SCORERS: :scorers
        LOGS: :logs

        def self?.values: -> ::Array[Braintrust::Models::ViewUpdateParams::view_type]
      end
    end
  end
end
