module Braintrust
  module Models
    type view_options =
      {
        column_order: ::Array[String]?,
        column_sizing: ::Hash[Symbol, Float]?,
        column_visibility: ::Hash[Symbol, bool]?,
        grouping: String?,
        layout: String?,
        row_height: String?
      }

    class ViewOptions < Braintrust::Internal::Type::BaseModel
      attr_accessor column_order: ::Array[String]?

      attr_accessor column_sizing: ::Hash[Symbol, Float]?

      attr_accessor column_visibility: ::Hash[Symbol, bool]?

      attr_accessor grouping: String?

      attr_accessor layout: String?

      attr_accessor row_height: String?

      def initialize: (
        ?column_order: ::Array[String]?,
        ?column_sizing: ::Hash[Symbol, Float]?,
        ?column_visibility: ::Hash[Symbol, bool]?,
        ?grouping: String?,
        ?layout: String?,
        ?row_height: String?
      ) -> void
    end
  end
end
