module Braintrust
  module Models
    type view_create_params =
      {
        name: String,
        object_id_: String,
        object_type: Braintrust::Models::ViewCreateParams::object_type,
        view_type: Braintrust::Models::ViewCreateParams::view_type?,
        deleted_at: Time?,
        options: Braintrust::Models::ViewOptions?,
        user_id: String?,
        view_data: Braintrust::Models::ViewData?
      }
      & Braintrust::request_parameters

    class ViewCreateParams < Braintrust::BaseModel
      extend Braintrust::RequestParameters::Converter
      include Braintrust::RequestParameters

      attr_accessor name: String

      attr_accessor object_id_: String

      attr_accessor object_type: Braintrust::Models::ViewCreateParams::object_type

      attr_accessor view_type: Braintrust::Models::ViewCreateParams::view_type?

      attr_accessor deleted_at: Time?

      attr_accessor options: Braintrust::Models::ViewOptions?

      attr_accessor user_id: String?

      attr_accessor view_data: Braintrust::Models::ViewData?

      def initialize:
        (
          name: String,
          object_id_: String,
          object_type: Braintrust::Models::ViewCreateParams::object_type,
          view_type: Braintrust::Models::ViewCreateParams::view_type?,
          deleted_at: Time?,
          options: Braintrust::Models::ViewOptions?,
          user_id: String?,
          view_data: Braintrust::Models::ViewData?,
          request_options: Braintrust::request_opts
        ) -> void
        | (
          ?Braintrust::Models::view_create_params | Braintrust::BaseModel data
        ) -> void

      def to_hash: -> Braintrust::Models::view_create_params

      type object_type =
        :organization
        | :project
        | :experiment
        | :dataset
        | :prompt
        | :prompt_session
        | :group
        | :role
        | :org_member
        | :project_log
        | :org_project

      class ObjectType < Braintrust::Enum
        ORGANIZATION: :organization
        PROJECT: :project
        EXPERIMENT: :experiment
        DATASET: :dataset
        PROMPT: :prompt
        PROMPT_SESSION: :prompt_session
        GROUP: :group
        ROLE: :role
        ORG_MEMBER: :org_member
        PROJECT_LOG: :project_log
        ORG_PROJECT: :org_project

        def self.values: -> ::Array[Braintrust::Models::ViewCreateParams::object_type]
      end

      type view_type =
        :projects
        | :experiments
        | :experiment
        | :playgrounds
        | :playground
        | :datasets
        | :dataset
        | :prompts
        | :tools
        | :scorers
        | :logs

      class ViewType < Braintrust::Enum
        PROJECTS: :projects
        EXPERIMENTS: :experiments
        EXPERIMENT: :experiment
        PLAYGROUNDS: :playgrounds
        PLAYGROUND: :playground
        DATASETS: :datasets
        DATASET: :dataset
        PROMPTS: :prompts
        TOOLS: :tools
        SCORERS: :scorers
        LOGS: :logs

        def self.values: -> ::Array[Braintrust::Models::ViewCreateParams::view_type]
      end
    end
  end
end
