module Braintrust
  module Models
    type view_retrieve_params =
      { object_id_: String, object_type: Braintrust::Models::acl_object_type }
      & Braintrust::request_parameters

    class ViewRetrieveParams < Braintrust::BaseModel
      extend Braintrust::RequestParameters::Converter
      include Braintrust::RequestParameters

      attr_accessor object_id_: String

      attr_accessor object_type: Braintrust::Models::acl_object_type

      def initialize:
        (
          object_id_: String,
          object_type: Braintrust::Models::acl_object_type,
          request_options: Braintrust::request_opts
        ) -> void
        | (
          ?Braintrust::Models::view_retrieve_params | Braintrust::BaseModel data
        ) -> void

      def to_hash: -> Braintrust::Models::view_retrieve_params
    end
  end
end
